
Language.CN = {	
	"pcModeTips"			:"点击此按钮将切换为桌面模式!",
	"mobileModeTips"		:"点击此按钮将切换为桌面模式!",
	"UASwitch"		:"模式切换",
	"UASwitchTips"			:"确认切换模式吗?模式切换之后,如出现兼容性问题,请关闭浏览器重新打开",
	"rebootTips"			:"您确认重启吗?",
	"ruleName"				:"过滤规则名称",
	"ruleSameMac"			:"相同的过滤MAC地址已存在!",
	"ruleNameErr"			:"过滤规则名称不正确!",
	"ruleNameLenErr"		:"过滤规则名称不能超过31个字符!",
	"ruleNameNULL"			:"过滤规则名称不能为空!",
	"maxEntry"				:"最大条目数为",
	"selectMacFilter"		:"请选择需要删除的MAC过滤规则!",
	"vlanChangeTips"		:"VLAN发生变化,设备将重新启动,请稍后...",
	"easyMeshWpsTips"		:"EasyMesh功能已开启,不建议关闭WPS功能,强行关闭该功能,WPS组网与正常WPS连接都将异常!!!",
	"sync with 2.4G"		:"同2.4G配置同步",
	"Log Management"		:"日志管理",
	"Log enalbe"			:"日志开关",
	"Log level"				:"日志等级",
	"Log Display"			:"日志查看",
	"Display level"			:"显示级别",
	"Log save"				:"保存日志",
	"Log clear"				:"清空日志",
	"Log_level 0"			:"紧急",
	"Log level 1"			:"警报",
	"Log level 2"			:"重要",
	"Log level 3"			:"错误",
	"Log level 4"			:"警告",
	"Log level 5"			:"注意",
	"Log level 6"			:"通知",
	"Log level 7"			:"调试",
	"logEnableTips"			:"注意:长期开启日志将影响设备性能!",
	"VLAN enable"			:"VLAN开关",
	"networkInitStatus"		:"正在获取网络状态...",
	"multi SSID Config"		:"Multi-SSID配置",
	"Service bind"			:"业务绑定",
	"quick config"			:"快速配置",
	"Hi"					:"您好!",
	"Guide Setting"			:"快速向导设置",
	"Guide Set"				:"快速向导设置",
	"Guide Jump"			:"跳过快速向导设置",
	"jumpGuideTips"			:"该操作将跳过向导设置,请确认?",
	"WanEthernetLinkTips"	:"提示:请接入设备WAN口!",	
	"rate"					:"速率",
	"realRate"				:"实时速率(kB/s)",
	"easyMeshNetworking"	:"正在组网",
	"easyMeshConned"		:"组网成功",
	"easyMeshIsDisconned"	:"组网失败",
	"repeaterIsDisconned"	:"中继失败",
	"repeaterConned"		:"中继成功",
	"repeaterConning"		:"尝试中继",
	"internetIsDisconned"	:"无法连接网络",
	"internetIsConned"		:"Internet正常",
	"cpu_mem_used"			:"CPU使用率/内存使用率",
	"channelOptizationTips"	:"'信道优化',通过信道扫描,找出当前环境中的最优信道;可以根据自己的需要,切换到最优信道,以提升WiFi使用体验.",
	"channelOptization"		:"信道优化",
	"bestChannel"			:"最优信道",
	"channelScan"			:"信道扫描",
	"channelScanFail"		:"信道扫描失败!",
	"isBestChannel"			:"当前信道已是最优信道",
	"channelScanTips"		:"执行该操作需工作在自动信道,检测到当前工作信道为固定信道,选择'确认',将切换信道为自动信道,下联设备有短暂断网的情况,请谨慎选择!",
	"chanOptTips"			:"当前信道不为最优信道,是否需要优化?选择'确认',将当前工作信道切换为最优信道,下联设备有短暂断网的情况,请谨慎选择!",
	"Bind lan"				:"端口绑定",
	"iptvSet"				:"IPTV设置",
	"macAddrFmtTips"		:"MAC地址格式不正确,正确格式为(AA:BB:CC:DD:EE:FF)",
	"qos_macAddrFmtTips"	:"MAC地址格式不正确,正确格式为(AABBCCDDEEFF)",
	"customMacAddr"			:"自定义MAC",
	"customDate"			:"自定义时间",
	"DMZ Configuration"				:"DMZ配置",
	"Host IP"						:"主机IP",
	"Virtual Server Configuration"	:"虚拟主机配置",
	"Outter Port"					:"外网端口",
	"Inner Port"					:"内网端口",
	"Host name"						:"主机名",
	"Host IP"						:"内网IP地址",
	"Operate"						:"操作",
	"Port forwarding"				:"端口映射",
	"Port forwarding rule"			:"端口映射规则",
	"Unkown device"					:"未知设备_",
	"User defined"					:"用户自定义",
	"Add maximum 10 rules"			:"最多添加10条规则",
	"Dmz host ip format error"		:"DMZ主机IP地址格式错误",
	"Please input host ip"			:"请输入DMZ主机IP地址",
	"Outter port error"				:"外网端口号错误!",
	"Outter port already exist"		:"该外网端口号已被使用!",
	"Inner port error"				:"内网端口号错误!",
	"Please input port"				:"请输入端口号",
	"Host ip format error"			:"内网IP地址格式错误",
	"Please input rule name"						:"请输入映射名称",
	"Name only support numbers, letters, _ and -"	:"映射名称仅支持数字,字母,\"_\"和\"-\"",
	"Name already exist"							:"此映射名称已被使用!",
	"Outter port format:"							:"外网端口可遵循以下格式:",
	"1.port range,use a colon between the start port and the end port, eg:300:500."	:"1、通信端口范围,在起始端口和结束端口间使用冒号':',如:300:500.",
	"2.Use commas between ports, eg:500,600."										:"2、单独的端口使用逗号',',如:500,600.",
	"3.Mixed use colon between and commas between,eg:300:500,600."					:"3、通信端口范围和单独的端口混合在一起,使用冒号':'和逗号',',如:300:500,600.",
	"mesh_workmode_apclint_tips0"	:"当前'工作模式'为中继模式,与Easymesh功能不能同时使用!!!",
	"gotoTips":				"请前往",	
	"mesh_workmode_apclint_tips1"	:"选择其他工作模式.",	
	"Mesh agent list"		:"MESH客户端列表",
	"unselectFile"			:"未选择任何文件",
	"networkingSuccTips"	:"EasyMesh组网成功,不允许修改从端WiFi参数!!",
	"wmmTitle"				:"WMM模式设置",
	"wmmMode"				:"WMM模式",
	"wmmModeNormal"			:"普通模式",
	"wmmModeAdv"			:"极速模式",
	"ipRangeRouteTips"		:"IP范围错误,请设置与Lan侧IP同一网段的IP地址",	
	"ipRangeBridgeTips"		:"IP范围错误,请设置与Wan侧IP同一网段的IP地址",	
	"ipRangeTips"			:"IP范围错误,起始IP地址不能大于结束IP地址",
	"entryExisted"			:"该条目已经存在!",
	"lockNetwork"			:"网络诊断",
	//"ispTips"				:"本设备限在移动宽带下使用,请切换网络后重试",
	"ispTips"				:"本路由器设备限制在中国移动宽带网络下使用,请切换网络重试",
	"alinkIf6Tips"			:"本路由器设备限制在中国移动宽带网络下使用,请切换网络重试",
	"pwd_pskTips"			:"双频合一功能未开启,默认将2.4G的WiFi密码作为路由器的管理密码",
	"accountTips"			:"将2.4G WiFi密码作为路由器管理密码",
	"reconnwiredTips"		:"所有WiFi均已关闭,请使用PC有线连接到设备登录管理界面或者复位设备!",
	"reconnectTips"			:"请重新连接WiFi",
	"ssidTips"				:"WiFi重启后,新的WiFi SSID为:",
	"configOK"				:"配置完成,待WiFi重新初始化完成,重新连接WiFi后即可访问互联网",
	"configGuide"			:"上网向导",
	"checking network"		:"正在检查您的网络环境,请等待...",
	"successTips"			:"成功连接互联网,可以正常上网了.",
	"failedNextTips"		:"连接互联网失败,请点击'下一步'重新设置您的网络!",		
	"failedTips"			:"连接互联网失败,请点击'上网设置'重新设置您的网络!",	
	"bootVersion"			:"uboot版本",
	"ApclintBndStrgTips"	:"当前上网方式为中继模式,为了设备的正常使用,不能开启双频优选功能!",
	"modeOptional"			:"(可选项)",
	"modeOption"			:"(必填项)",	
	"macFMT"				:"(格式:AABBCCDDEEFF)",
	"saving"				:"正在保存参数,请稍后...",
	"routerMode"				:"路由模式",
	"bridgeMode"			:"桥接模式",
	"repeaterMode"			:"中继模式",
	"ssidEnable"			:"启用",
	"ssidDisable"			:"停用",	
	"LanSegmentFault"		:"LAN侧IP地址与WAN侧IP地址不允许设置为同一IP地址或同一网段!",
	"LanWanSegmentFault"	:"WAN侧IP地址与LAN侧IP地址不允许设置为同一IP地址或同一网段!",
	"LANIPRangeError"		:"请设置管理IP地址在DHCP地址池范围之外的地址!",
	"ipSegmentFault"		:"WAN侧IP地址与网关不在同一网段!",
	"checkSuming"			:"正在校验文件,请稍等...",
	"checkSumFail"			:"升级文件校验失败,请确认是否为正确的升级文件.",
	"checkSumRomfileFail"	:"配置文件校验失败,请确认是否为正确的配置文件.",
	"upgradeFail"			:"升级失败,请确认是否为正确的升级文件.",	
	"notKTUboot"			:"升级文件非特定固件,请确认是否为正确的升级文件.",	
	"upLoadSucess"			:"文件上传成功",		
	"modIsExited"			:"修改后的LAN/SSID与已经存在的冲突,请调整.",
	"limitU"				:"(单位:Kbps)",
	"iplimitU"				:"(单位:512Kbps)",
	"isExitedTip"			:"已经存在,不可重复添加!",
	"isZeroTip"				:"请填入大于0的数",
	"queenLmt"				:"最多有６个队列,请调整",
	"ipFmtTip"				:"IP地址格式不正确,请填写正确的IP地址",
	"ip6addrTip"			:"IPv6地址最小值与最大值必须相同",
	"delTip"				:"您确认要删除吗?",
	"lmtTotalTip"			:"带宽之和不能大于上行总带宽,请调整",
	"ipRange"				:"IP范围",
	"speedLMT"				:"限速",
	"limitClose"			:"关闭",
	"limitMode"				:"请选择限速方式",	
	"limitInter"			:"基于用户接口限速",
	"limitIp"				:"基于用户侧设备IP地址段限速",
	"limitMAC"				:"基于用户侧设备MAC地址限速",	
	"qosUPSet"				:"QOS上行配置",
	"speedTitle"			:"限速配置",
	"LimitSet"				:"上下行限速模式设置",
	"downLimitSet"			:"下行限速模式设置",	
	"upLimit"				:"上行数据限速模式",
	"downLimit"				:"下行数据限速模式",
	"upgrading"				:"正在升级...",
	"fileNULLTip"    		:"你必须选择一个升级文件!",
	"fileTypeTip"			:"文件格式错误!",
	"attack"				:"攻击保护",	
	"attackSet"				:"攻击保护设置",
	"securityLeval"			:"安全级别",
	"secLevelSet"			:"防火墙等级配置",
	"low"					:"低级",
	"medium"				:"中级",
	"high"					:"高级",
	"wepDisableTip"			:"加密模式为WEP时,无法开启WPS功能!",
	"isInWPSing"			:"当前WPS处于工作状态,无法保存设置!请按STOP WPS按钮后,再尝试保存设置.",
	"wpsSwitch"				:"WPS开关",
	"startWps"				:"请在2分钟内启动WPS连接.",
	"pinReg"				:"请输入正确规则的PIN码:奇数位和的3倍加上偶数位的和是10的整数倍",
	"pinLen"				:"请输入8位数字PIN码",
	"pinError"				:"PIN码应当是0-9之间的整数",
	"pin_generate"			:"生成PIN码",
	"wpsMode"				:"WPS 模式",
	"fileType"				:"文件类型",
	"menuIndexTip"			:"首页",
	"menuWanTip"			:"上网设置",
	"menuLanTip"			:"局域网设置",
	"menuWiFiTip"			:"WiFi设置",
	"menuAdvTip"			:"更多设置",
	"Performance Mode"        : "性能模式",
	"Restore Tips"        : "所有设置将恢复到出厂默认状态,请确认.",
	"Beacon Interval"        : "Beacon信标间隔",
	"DTIM Period"        : "DTIM间隔",
	"RTS Threshold"        : "RTS Threshold",
	"AMSDU"        : "A-MSDU",
	"TxBurst"        : "TxBurst",
	"PktAggregate"        : "Packet Aggregate",
	"Igmp Snooping"        : "IGMP Snooping",
	"HT Guard Interval"        : "保护间隔",
	"long"        : "Long",
	"short"        : "Short",
	"ht_auto"        : "Auto",
	"ManagmentAddr Set"        : "管理地址设置",
	"leaseTime Invalid Tips"        : "只支持数字输入,且必须在提示范围内.",
	"IP Invalid Tips"        : "只支持点分十进制IP地址.",
	"common Set"        : "常用设置",
	"sysInfo"        : "系统信息",
	"arp Bind"        : "DHCP静态IP",
	"Static address list"   :"静态地址列表",
	"macFmtTip"				:"(格式:AA:BB:CC:DD:EE:FF)",
	"mac Clone"        : "MAC克隆",
	"WiFiAdvSet"        : "WiFi高级设置",
	"wps Set"        : "WPS设置",
	"selected Plugin"        : "精选插件",
	"Wireless client"        : "无线客户端",
	"qos Limit"        : "QOS限速",
	"One-button Reboot"        : "一键重启",
	"safe Center"        : "安全中心",
	"Setting Mnt"        : "配置管理",
	"Smart Home"        : "智能家居",
	"Reserved Interface"        : "预留接口",
	"Network Sec"        : "网络安全",
	"vpnThrough"        : "VPN穿越",
	"IPsec"        : "IPsec透传",
	"L2TP_alg"        : "L2TP透传",
	"PPTP"        : "PPTP透传",
	"paramEdit"        : "参数编辑",
	"paramView"        : "参数查看",
	"scaningTips"        : "正在扫描,请稍等...",
	"Scaning..."        : "正在扫描",
	"Wire Repeater"        : "无线中继",
	"EasyMesh repeater"		:"EasyMesh 中继",
	"Wire Checked"        : "选择",
	"Wire WLAN SSID"        : "中继上行WLAN SSID",
	"WireSecTips"        : "手动设置中继上行WLAN安全参数",
	"WireRepeaterTips"        : "WLAN下行与WLAN中继上行使用相同的无线配置",
	"WireTips"        : "提示:设置后,设备将会自动切换到 WLAN 上行模式.",
	"siteScan"        : "信号扫描",
	"WIFI Disabled Tips"        : "已关闭,若需要开启,请开启无线开关或者开启下方ssid开关,开启对应的ssid",
	"ssid Switch"        : "SSID开关",
	"SSID Change"        : "SSID切换",
	"macClone Switch"        : "MAC克隆开关",
	"Some illegal operations will not be saved. Such as IP is out of DHCP Pool, Device Mac or IP set repeat"        : "一些非法操作,将不会被保存,例如IP地址超出DHCP地址池范围,MAC地址或者IP地址重复设置",
	"Wire SSID"			:"上行SSID",
	"DisConnected"        : "连接已断开",
	"Browser Tips"        : "为了更好的用户体验,请升级您的浏览器至新版本",
	"download Tips"        : "下载和家亲APP管理路由器",
	"Passwd Tips"        : "忘记密码",
	"Login Tips"        : "请按复位键恢复出厂设置,然后使用铭牌上的WiFi密码登录设备",
	"online_staNum"        : "在线设备",
	"sta Unit"        : "台",
	"net_Info"        : "联网信息",
	"health"        : "设备健康指数",
	"health Tips"         : "优",
	"health lev 1"        : "优",
	"health lev 2"        : "良",
	"health lev 3"        : "中",
	"health lev 4"        : "差",
	"psk Tips"        : "默认加密方式为WPA/WPA2混合加密,密钥长度不能低于8位",
	"RSSI"        : "rssi",
	"File Size"        : "文件大小",
	"upgrade_tips"        : "过程中切勿断电!",
	"Bandwidth_enable"        : "带宽控制使能",
	"Bandwidth_Mnt"        : "带宽控制",
	"UpStream"        : "上传速率(Kbps)",
	"DownStream"        : "下载速率(Kbps)",
	"Network Switch"        : "网络开关",
	"Parent Control"        : "家长控制(仅对受控设备有效)",
	"Device Reboot"        : "设备重启",
	"Device Reset"        : "设备复位",
	"Device Reboot tips"	:"点击此按钮将重启设备!",
	"Device Reset tips"		:"点击此按钮将复位设备!",
	"Device rebooting please wait"	:"设备重启中,请等待...",
	"Protect Net"        : "防止蹭网",
	"NetInfo"        : "流量统计",
	"Separate Clients Tip"        : "开启隔离客户端后,各个连接的用户间也不能相互访问,起到隔离作用,有利于抵御外部攻击",
	"WMM Mode Tip"        : "WMM允许无线通信根据数据类型定义优先级范围.时间敏感的数据,如视频/音频数据比普通数据,有更高的优先级",
	"wireless radio"        : "无线频段",
	"Plugin Managment"        : "更多插件",
	"Plugin Switch"        : "插件开关",
	"Plugin State"        : "插件状态",
	"Plugin Check"        : "插件安全检测",
	"plugin_safe"        : "安全",
	"plugin_not_safe"        : "不安全",
	"white list"        : "白名单",
	"WhiteList"        : "白名单",
	"BlackList"        : "黑名单",
	"black list"        : "黑名单",
	"(%d minute window, %d second interval)"        : "(%d分钟信息,%d秒刷新)",
	"(%s available)"        : "(%s 可用)",
	"(empty)"        : "(空)",
	"(no interfaces attached)"        : "(未连接接口)",
	"-- Additional Field --"        : "-- 更多选项 --",
	"-- Please choose --"        : "-- 请选择 --",
	"-- custom --"        : "-- 自定义 --",
	"1 Minute Load:"        : "1分钟负载:",
	"15 Minute Load:"        : "15分钟负载:",
	"5 Minute Load:"        : "5分钟负载:",

	"AICCU (SIXXS)"        : "",
	"APN"        : "APN",
	"Advanced"        : "高级",
	"AR Support"        : "AR支持",
	"ARP retry threshold"        : "ARP重试阈值",
	"ATM Bridges"        : "ATM桥接",
	"ATM Virtual Channel Identifier (VCI)"        : "ATM虚拟通道标识(VCI)",
	"ATM Virtual Path Identifier (VPI)"        : "ATM虚拟路径标识(VPI)",
	"ATM bridges expose encapsulated ethernet in AAL5 connections as virtual Linux network interfaces which can be used in conjunction with DHCP or PPP to dial into the provider network."        : "ATM桥是以AAL5协议封装以太网的虚拟Linux网桥,用于协同DHCP或PPP来拨号连接到网络运营商.",
	"ATM device number"        : "ATM设备号码",
	"Access Concentrator"        : "接入集中器",
	"Access Point"        : "接入点AP",
	"Action"        : "动作",
	"Actions"        : "动作",
	"Activate this network"        : "激活此网络",
	"Active Connections"        : "活动连接",
	"Active DHCP Leases"        : "已分配的DHCP租约",
	"Active DHCPv6 Leases"        : "已分配的DHCPv6租约",
	"Ad-Hoc"        : "点对点Ad-Hoc",
	"Add"        : "添加",
	"Add success"        : "添加成功",
	"Remove success"        : "移除成功",
	"Add Blacklist"        : "添加到黑名单",
	"Add local domain suffix to names served from hosts files"        : "添加本地域名后缀到HOSTS文件中的域名",
	"Add new interface..."        : "添加新接口...",
	"Additional Hosts files"        : "额外的HOSTS文件",
	"Address"        : "地址",
	"Address to access local relay bridge"        : "接入本地中继桥的地址",
	"Administration"        : "管理权",
	"Alert"        : "警戒",
	"Allow all except listed"        : "仅允许列表外",
	"Allow listed only"        : "仅允许列表内",
	"Allow localhost"        : "允许本机",
	"Allow remote hosts to connect to local SSH forwarded ports"        : "允许远程主机连接到本地SSH转发端口",
	"Allow root logins with password"        : "root权限登录",
	"Allow the <em>root</em> user to login with password"        : "允许root用户凭密码登录",
	"Allow upstream responses in the 127.0.0.0/8 range, e.g. for RBL services"        : "允许127.0.0.0/8回环范围内的上行响应,例如:RBL服务",
	"Always announce default router"        : "总是广播默认路由",
	"An additional network will be created if you leave this unchecked."        : "取消选中将会另外创建一个新网络,而不会覆盖当前网络设置",
	"Announce as default router even if no public prefix is available."        : "即使没有可用的公共前缀也广播默认路由",
	"Announced DNS domains"        : "广播的DNS域名",
	"Announced DNS servers"        : "广播的DNS服务器",
	"Antenna 1"        : "天线 1",
	"Antenna 2"        : "天线 2",
	"Antenna Configuration"        : "天线配置",
	"Any zone"        : "任意区域",
	"Apply"        : "应用",
	"Applying..."        : "正在应用",
	"Checking..."        : "检测中",
	"Applying changes"        : "正在应用更改",
	"Assign a part of given length of every public IPv6-prefix to this interface"        : "给每个公共IPv6前缀分配指定长度的固定部分",
	"Assign interfaces..."        : "分配接口...",
	"Assign prefix parts using this hexadecimal subprefix ID for this interface."        : "",
	"Associated Stations"        : "无线客户端列表",
	"Wired Associated Stations"		:"有线客户端列表",
	"Atheros 802.11%s Wireless Controller"        : "Qualcomm/Atheros 802.11%s 无线网卡",
	"Authentication"        : "认证",
	"Authoritative"        : "授权的唯一DHCP服务器",
	"Authorization Required"        : "需要授权",
	"Auto Refresh"        : "自动刷新",
	"Automatic"        : "自动",
	"Automatic Homenet (HNCP)"        : "自动家庭网络(HNCP)",
	"Available"        : "可用",
	"Available packages"        : "可用软件包",
	"Average:"        : "平均:",
	"BSSID"        : "BSSID",
	"Back"        : "返回",
	"Back to Overview"        : "返回至概况",
	"Back to configuration"        : "返回至配置",
	"Back to overview"        : "返回至概况",
	"Back to scan results"        : "返回至扫描结果",
	"Background Scan"        : "后台搜索",
	"Backup / Flash Firmware"        : "备份/升级",
	"Backup / Restore"        : "备份/恢复",
	"Backup file list"        : "文件备份列表",
	"Bad address specified!"        : "指定了错误的地址!",
	"Band"        : "模式",
	"User Set"        : "用户管理",
	"Device Set"        : "设备管理",
	"Time Set"        : "时间管理",
	"Time"        : "时间",
	"Log Set"        : "日志管理",
	"Timeout Set"        : "超时管理",
	"Bitrate"        : "传输速率",
	"Bogus NX Domain Override"        : "忽略虚假空域名解析",
	"Bridge"        : "桥接",
	"Bridge interfaces"        : "桥接接口",
	"Bridge unit number"        : "桥接号",
	"Bring up on boot"        : "开机自动运行",
	"Broadcom 802.11%s Wireless Controller"        : "Broadcom 802.11%s 无线网卡",
	"Broadcom BCM%04x 802.11 Wireless Controller"        : "Broadcom BCM%04x 802.11 无线网卡",
	"Buffered"        : "已缓冲",
	"Buttons"        : "按键",
	"CPU"        : "CPU",
	"CPU usage (%)"        : "CPU使用率(%)",
	"Cancel"        : "取消",
	"Submit"        : "确认",
	"Category"        : "分类",
	"Chain"        : "链",
	"Changes"        : "修改数",
	"Changes applied."        : "更改已应用",
	"Changes the administrator password for accessing the device"        : "修改访问设备的管理员密码",
	"Channel"        : "信道",
	"Check"        : "检查",
	"Checksum"        : "校验值",

	"Cipher"        : "算法",
	"Client"        : "客户端Client",
	"Client ID to send when requesting DHCP"        : "请求DHCP时发送的客户ID",
	"Close inactive connection after the given amount of seconds, use 0 to </br>persist connection"        : "定时关闭非活动链接(秒),0为持续连接",
	"Close list..."       			: "关闭列表...",
	"Collecting data..."       		: "正在收集数据...",
	"Command"        				: "进程命令",
	"Common Configuration"        	: "一般设置",
	"Compression"        			: "压缩",
	"Configuration"        			: "配置",
	"Configuration applied."        : "配置已应用",
	"Configuration files will be kept."        : "配置文件将被保留.",
	"Confirmation"       : "确认密码",
	"Connect"        : "连接",
	"Connected"        : "已连接",
	"Connection Limit"        : "接入数量限制",
	"Connections"        : "链接",
	"Country"        : "国家",
	"Country Code"        : "国家代码",
	"Cover the following interface"        : "包括以下接口",
	"Cover the following interfaces"        : "包括以下接口",
	"Create / Assign firewall-zone"        : "创建/分配 防火墙区域",
	"Create Interface"        : "创建新接口",
	"Create a bridge over multiple interfaces"        : "在多个接口上创建桥接",
	"Critical"        : "致命错误",
	"Cron Log Level"        : "Cron日志级别",
	"Custom Interface "       : "自定义接口",
	"Custom delegated IPv6-prefix"        : "",
	"DHCP Leases"        : "DHCP分配",
	"DHCP Server"        : "DHCP服务器",
	"DHCP and DNS"        : "DHCP/DNS",
	"DHCP client"        : "DHCP客户端",
	"DHCP-Options"        : "DHCP-选项",
	"DHCPv6 Leases"        : "DHCPv6分配",
	"DHCPv6 client"        : "DHCPv6客户端",
	"DHCPv6-Mode"        : "DHCPv6模式",
	"DHCPv6-Service"        : "DHCPv6服务",
	"DNS"        : "DNS",
	"DNS forwardings"        : "DNS转发",
	"DNS-Label / FQDN"        : "",
	"DS-Lite AFTR address"        : "",
	"DUID"        : "DUID（DHCP唯一标识符）",
	"Debug"        : "调试",
	"Default %d"        : "默认%d",
	"Default gateway"        : "默认网关",
	"Default state"        : "默认状态",
	"Define a name for this network."        : "为网络定义名称",
	"Delete"        : "删除",
	"DeleteAll"        : "删除全部",
	"Delete this interface"        : "删除此接口",
	"Delete this network"        : "删除此网络",
	"Description"        : "描述",
	"Design"        : "主题",
	"Destination"        : "目标地址",
	"Device"        : "设备",
	"Device Configuration"        : "设备配置",
	"Diagnostics"        : "网络诊断",
	"Directory"        : "目录",
	"Disable"        : "禁用",
	"Disable DNS setup"       : "停用DNS设定",
	"Disable HW-Beacon timer"        : "停用 HW-Beacon 计时器",
	"Disabled"        : "禁用",
	"Discard upstream RFC1918 responses"        : "丢弃RFC1918上行响应数据",
	"Displaying only packages containing"        : "只显示有内容的软件包",
	"Distance Optimization"        : "距离优化",
	"Distance to farthest network member in meters."        : "最远客户端的距离(米).",
	"Diversity"        : "分集",
	"Do not cache negative replies, e.g. for not existing domains"        : "不缓存无用的回应, 比如:不存在的域.",
	"Do not forward requests that cannot be answered by public name servers"        : "不转发公共域名服务器无法回应的请求",
	"Do not forward reverse lookups for local networks"        : "不转发反向查询本地网络的Lookups命令",
	"Do not send probe responses"        : "不回送探测响应",
	"Domain required "       : "忽略空域名解析",
	"Domain whitelist"        : "域名白名单",
	"Download backup"        : "下载备份",
	"Dropbear Instance"        : "Dropbear设置",
	"Dynamic tunnel"        : "动态隧道",
	"EAP-Method"        : "EAP-Method",
	"Edit"        : "修改",

	"Edit this interface"        : "修改此接口",
	"Edit this network"        : "修改此网络",
	"Emergency"        : "紧急",
	"Enable"        : "启用",
	"Enable HE.net dynamic endpoint update"        : "启用HE.net动态终端更新",
	"Enable IPv6 negotiation on the PPP link"        : "在PPP链路上启用IPv6协商",
	"Enable Jumbo Frame passthrough"        : "启用巨型帧透传",
	"Enable NTP client"        : "启用NTP客户端",
	"Enable TFTP server"        : "启用TFTP服务器",
	"Enable VLAN functionality"        : "启用VLAN",
	"Enable learning and aging"        : "启用智能交换学习",
	"Enable this mount"        : "启用挂载点",
	"Enable this swap"        : "启用交换区",
	"Enable/Disable"        : "启用/禁用",
	"Enabled"        : "启用",
	"Enables the Spanning Tree Protocol on this bridge"        : "在此桥接上启用生成协议树",
	"Encapsulation mode"        : "封装模式",
	"Encryption"        : "加密",
	"Erasing..."        : "擦除中...",
	"Error"        : "错误",
	"Ethernet Adapter"        : "以太网适配器",
	"Ethernet Switch"        : "以太网交换机",
	"Expand hosts"        : "扩展HOSTS文件中的主机后缀",
	"Expires"        : "到期时间",
	"External"        : "",
	"External system log server"        : "远程log服务器",
	"External system log server port"        : "远程log服务器端口",
	"Fast Frames"        : "快速帧",
	"File"        : "文件",
	"Filename of the boot image advertised to clients"        : "向客户端通告的启动镜像文件名",
	"Filesystem"        : "文件系统",
	"Filter"        : "过滤器",
	"Filter private"        : "过滤本地包",
	"Filter useless"        : "过滤无用包",
	"Find and join network"        : "搜索并加入网络",
	"Find package"        : "查找软件包",
	"Finish"        : "完成",
	"Firewall"        : "防火墙",
	"Firewall Settings"        : "防火墙设置",
	"Firewall Status"        : "防火墙状态",
	"Firmware Version"        : "固件版本",
	"Fixed source port for outbound DNS queries"        : "指定的DNS查询源端口",
	"Flags"        : "标识",
	"Flash Firmware"        : "刷新固件",
	"Flash..."        : "刷写固件...",
	"Flash new firmware image"        : "刷写新的固件",
	"Flash operations"        : "刷新操作",
	"Flashing..."        : "刷写中...",
	"Force"        : "强制开启DHCP",
	"Force 40MHz mode"        : "强制40MHz带宽",
	"Force CCMP (AES)"        : "强制使用CCMP(AES)加密",
	"Force DHCP on this network even if another server is detected."        : "强制开启DHCP.",
	"Force TKIP"        : "强制使用TKIP加密",
	"Force TKIP and CCMP (AES)"        : "TKIP和CCMP(AES)混合加密",
	"Forward DHCP traffic"        : "转发DHCP数据包",
	"Forward broadcast traffic"        : "转发广播数据包",
	"Forwarding mode"        : "转发模式",
	"Fragmentation Threshold"        : "分片阈值",
	"Frame Bursting"        : "帧突发",
	"Free"        : "空闲数",
	"Free space"        : "空闲空间",
	"GHz"        : "GHz",
	"GPRS only"        : "仅GPRS",
	"Gateway"        : "网关",
	"Gateway ports"        : "网关端口",
	"General Settings"        : "基本设置",
	"General Setup"        : "基本设置",
	"Generate archive"        : "生成备份",
	"Generic 802.11%s Wireless Controller"        : "Generic 802.11%s 无线网卡",
	"Given password confirmation did not match, password not changed!"        : "由于密码验证不匹配,密码没有更改!",
	"Global network options"        : "全局网络选项",
	"Go to password configuration..."        : "跳转到密码配置页...",
	"Go to relevant configuration page"        : "跳转到相关的配置页面",
	"Guest"        : "访客",
	"HE.net password"        : "HE.net密码",
	"HE.net username"        : "HE.net用户名",
	"HT mode (802.11n)"        : "带宽",
	"Handler"        : "处理程序",
	"Hang Up"        : "挂起",
	"Here you can configure the basic aspects of your device like its hostname or </br>the timezone."        : "配置路由器的部分基础信息.",
	"Here you can paste public SSH-Keys (one per line) for SSH public-key </br>authentication."        : "SSH公共密钥认证(每行一个密钥).",
	"Hermes 802.11b Wireless Controller"        : "Hermes 802.11b 无线网卡",
	"Host entries"        : "主机目录",
	"Host expiry timeout"        : "主机到期超时",
	"Host-<abbr title=\"Internet Protocol Address\">IP</abbr> or Network"        : "主机IP或网络",
	"Hostname"        : "主机名",
	"Hostname to send when requesting DHCP"        : "请求DHCP时发送的主机名",
	"Hostnames"        : "主机名",
	"IP address"        : "IP地址",
	"IPv4"        : "IPv4",
	"WAN Status"			:"WAN状态",
	"IPv4 Firewall"        : "IPv4防火墙",
	"IPv4 WAN Status"        : "IPv4 WAN状态",
	"IPv4 address"        : "IP地址",
	"IPv4 and IPv6"        : "IPv4和IPv6",
	"IPv4 assignment length"        : "分配IPv4长度",
	"IPv4 broadcast"        : "IPv4广播",
	"IPv4 gateway"        : "网关地址",
	"IPv4 netmask"        : "子网掩码",
	"IPv4 only"        : "仅IPv4",
	"IPv4 prefix length"        : "IPv4地址前缀长度",
	"IPv4-Address"        : "IPv4-地址",
	"IPv6"        : "IPv6",
	"IPv6 Firewall"        : "IPv6防火墙",
	"IPv6 Settings"        : "IPv6设置",
	"IPv6 ULA-Prefix"        : "IPv6 ULA前缀",
	"IPv6 WAN Status"        : "IPv6 WAN状态",
	"IPv6 address"        : "IPv6地址",
	"IPv6 assignment hint"        : "",
	"IPv6 assignment length"        : "IPv6分配长度",
	"IPv6 gateway"        : "IPv6默认网关",
	"IPv6 netmask"        : "IPv6子网掩码",
	"IPv6 only"        : "仅IPv6",
	"IPv6 prefix"        : "IPv6地址前缀",
	"IPv6 prefix length"        : "IPv6地址前缀长度",
	"IPv6 routed prefix"        : "IPv6路由前缀",
	"IPv6-Address"        : "IPv6-地址",
	"IPv6-in-IPv4 (RFC4213)"        : "IPv6-in-IPv4 (RFC4213)",
	"IPv6-over-IPv4 (6rd)"        : "IPv6-over-IPv4 (6rd)",
	"IPv6-over-IPv4 (6to4)"        : "IPv6-over-IPv4 (6to4)",
	"Identity"        : "鉴权",
	"Ignore interface"        : "关闭DHCP",
	"Ignore resolve file"        : "忽略解析文件",
	"Image"        : "固件文件",
	"In"        : "入口",
	"Inactivity timeout"        : "活动超时",
	"Inbound:"        : "入站:",
	"Info"        : "信息",
	"Initscript"        : "启动脚本",
	"Initscripts"        : "启动脚本",
	"Install"        : "安装",
	"Install iputils-traceroute6 for IPv6 traceroute"        : "安装iputils-traceroute6以进行IPv6 traceroute",
	"Install package %q"        : "安装软件包%q",
	"Install protocol extensions..."        : "安装扩展协议...",
	"Installed packages"        : "已安装软件包",
	"Interface"        : "接口",
	"Interface Configuration"        : "接口配置",
	"Interface Overview"        : "接口总览",
	"Interface is reconnecting..."        : "正在重新连接接口...",
	"Interface is shutting down..."        : "正在关闭接口...",
	"Interface not present or not connected yet."        : "接口不存在或未连接",
	"Interface reconnected"        : "接口已重新连接",
	"Interface shut down"        : "接口已关闭",
	"Interfaces"        : "接口",
	"Internal Server Error"        : "内部服务器错误",
	"Invalid"        : "无效",
	"Invalid VLAN ID given! Only IDs between %d and %d are allowed."        : "无效的VLAN ID! 只有 %d 和 %d 之间的ID有效.",
	"Invalid VLAN ID given! Only unique IDs are allowed"        : "无效的VLAN ID! 只允许唯一的ID.",
	"Invalid username and/or password! Please try again."        : "无效的用户名或密码! 请重试.",
	"It appears that you are trying to flash an image that does not fit into the </br>flash memory, please verify the image file!"        : "将要刷新的固件与本路由器不兼容,请重新验证固件文件.",
	"Java Script required!"        : "需要Java Script!",
	"Join Network"        : "加入网络",
	"Join Network: Settings"        : "加入网络:设置",
	"Join Network: Wireless Scan"        : "加入网络:搜索无线",
	"Keep settings"        : "保留配置",
	"Kernel Log"        : "内核日志",
	"Kernel Version"        : "内核版本",
	"Key"        : "密码",
	"Key #%d"        : "密码 #%d",
	"Kill"        : "强制关闭",
	"L2TP"        : "L2TP",
	"L2TP Server"        : "L2TP服务器",
	"LCP echo failure threshold"        : "LCP响应故障阈值",
	"LCP echo interval"        : "LCP响应间隔",
	"LLC"        : "LLC",
	"Label"        : "卷标",
	"Language"        : "语言",
	"Language and Style"        : "语言和界面",
	"Lease validity time"        : "有效租期",
	"Leasefile"        : "租约文件",
	"Leasetime"        : "租约时间",
	"Leasetime remaining"        : "剩余租期",
	"Leave empty to autodetect"        : "留空则自动探测",
	"Leave empty to use the current WAN address"        : "留空则使用当前WAN地址",
	"Legend:"        : "图例:",
	"Limit"        : "客户数",
	"Line Attenuation"        : "",
	"Line Speed"        : "线路速率",
	"Line State"        : "线路状态",
	"Link On"        : "活动链接",
	"List of <abbr title=\"Domain Name System\">DNS</abbr> servers to forward </br>requests to"        : "将指定的域名DNS解析转发到指定的DNS服务器（按照示例填写）",
	"List of domains to allow RFC1918 responses for"        : "允许RFC1918响应的域名列表",
	"List of hosts that supply bogus NX domain results"        : "允许虚假空域名响应的服务器列表",
	"Listen only on the given interface or, if unspecified, on all"        : "监听指定的接口；未指定则监听全部",
	"Listening port for inbound DNS queries"        : "入站DNS查询端口",
	"Load"        : "负载",
	"Load Average"        : "平均负载",
	"Loading"        : "加载中",
	"Local IPv4 address"        : "本地IPv4地址",
	"Local IPv6 address"        : "本地IPv6地址",
	"Local Startup"        : "本地启动脚本",
	"Local Time"        : "本地时间",
	"Local domain"        : "本地域名",
	"Local domain specification. Names matching this domain are never forwarded </br>and are resolved from DHCP or hosts files only"        : "本地域名规则.从不转发和处理只源自DHCP或HOSTS文件的本地域名数据",
	"Local domain suffix appended to DHCP names and hosts file entries"        : "本地域名后缀将添加到DHCP和HOSTS文件条目",
	"Local server"        : "本地服务器",
	"Localise hostname depending on the requesting subnet if multiple IPs are </br>available"        : "如果有多个IP可用,则根据请求来源的子网来本地化主机名",
	"Localise queries"        : "本地化查询",
	"Locked to channel %s used by: %s"        : "信道道已被锁定为 %s,因为该信道被 %s 使用",
	"Log output level"        : "日志记录等级",
	"Log queries"        : "日志查询",
	"Logging"        : "日志",
	"Login"        : "登录",
	"AdminPassword"		: "管理员密码",
	"UsernameTip"	:	"请输入用户名",
	"PasswordTip"	:	"请输入管理密码",
	"Logout"        : "退出",
	"Lowest leased address as offset from the network address(10~253)."        : "网络起始分配地址(10~253).",
	"MAC-Address"        : "MAC-地址",
	"MAC-Address Filter"        : "MAC-地址过滤",
	"MAC-Filter"        : "MAC-过滤",
	"MAC-List"        : "MAC-列表",
	"MB/s"        : "MB/s",
	"MHz"        : "MHz",
	"MTU"        : "MTU",
	"Maximum Rate"        : "最高速率",
	"Maximum allowed number of active DHCP leases"        : "允许的最大DHCP租用数",
	"Maximum allowed number of concurrent DNS queries"        : "允许的最大并发DNS查询数",
	"Maximum allowed size of EDNS.0 UDP packets"        : "允许的最大EDNS.0 UDP报文大小",
	"Maximum amount of seconds to wait for the modem to become ready"        : "调制解调器就绪的最大等待时间(秒)",
	"Maximum hold time"        : "最大持续时间",
	"Maximum number of leased addresses,the minimum number of allocation is 1."        : "最大地址分配数量,最小分配数量为1.",
	"Mbit/s"        : "Mbit/s",
	"Memory"        : "内存",
	"Memory usage (%)"        : "内存使用率(%)",
	"Metric"        : "跃点数",
	"Minimum Rate"        : "最低速率",
	"Minimum hold time"        : "最低持续时间",
	"Missing protocol extension for proto %q"        : "缺少协议%q的协议扩展",
	"Mode"        : "模式",
	"Model"        : "",
	"Modem device"        : "调制解调器节点",
	"Modem init timeout"        : "调制解调器初始化超时",
	"Monitor"        : "监听Monitor",
	"Mount Entry"        : "挂载项目",
	"Mount Point"        : "挂载点",
	"Mount Points"        : "挂载点",
	"Mount Points - Mount Entry"        : "挂载点-存储区",
	"Mount Points - Swap Entry"        : "挂载点-交换区",
	"Mount Points define at which point a memory device will be attached to the </br>filesystem"        : "配置存储设备挂载到文件系统中的位置和参数.",
	"Mount options"        : "挂载选项",
	"Mount point"        : "挂载点",
	"Mounted file systems"        : "已挂载的文件系统",
	"Move down"        : "下移",
	"Move up"        : "上移",
	"Multicast Rate"        : "多播速率",
	"Multicast address"        : "多播地址",
	"NAS ID"        : "NAS ID",
	"NDP-Proxy"        : "NDP-代理",
	"NTP server candidates"        : "候选NTP服务器",
	"Name"        : "名称",
	"Name of the new interface"        : "新接口的名称",
	"Name of the new network"        : "新网络的名称",
	"Navigation"        : "导航",
	"Netmask"        : "子网掩码",
	"Network"        : "网络",
	"Network Utilities"        : "网络工具",
	"Network boot image"        : "网络启动镜像",
	"Network without interfaces."        : "无接口的网络.",
	"Next ?"        : "下一步 ?",
	"Next"        : "下一步",
	"Prev"		  :"上一步",
	"No DHCP Server configured for this interface"        : "本接口未配置DHCP服务器",
	"No chains in this table"        : "本表中没有链",
	"No files found"        : "未找到文件",
	"No information available"        : "无可用信息",
	"No negative cache"        : "禁用无效信息缓存",
	"No network configured on this device"        : "本设备未配置网络",
	"No network name specified"        : "未指定网络名",
	"No package lists available"        : "无可用软件列表",
	"No password set!"        : "未设置密码!",
	"No rules in this chain"        : "本链没有规则",
	"No zone assigned"        : "未指定区域",
	"Noise"        : "噪声",
	"Noise Margin"        : "噪声容限",
	"Noise:"        : "噪声:",
	"None"        : "无",
	"Normal"        : "正常",
	"Not Found"        : "未找到",
	"Not associated"        : "未关联",
	"Not connected"        : "未连接",
	"Note: Configuration files will be erased."        : "注意:配置文件将被删除.",
	"Notice"        : "注意",
	"Nslookup"        : "Nslookup",
	"OK"        : "OK",
	"OPKG-Configuration"        : "OPKG-配置",
	"Off-State Delay"        : "关闭时间",
	"On-State Delay"        : "通电时间",
	"One of hostname or mac address must be specified!"        : "请指定主机名或MAC地址!",
	"One or more fields contain invalid values!"        : "一个或多个选项值有误!",
	"One or more required fields have no value!"        : "一个或多个必选项值为空!",
	"Open list..."        : "打开列表...",
	"Option changed"        : "修改的选项",
	"Option removed"        : "移除的选项",
	"Options"        : "选项",
	"Other:"        : "其余:",
	"Out"        : "出口",
	"Outbound:"        : "出站:",
	"Outdoor Channels"        : "户外频道",
	"Override MAC address"        : "克隆PC MAC",
	"Override MTU"        : "设置MTU",
	"Override the gateway in DHCP responses"        : "更新网关",
	"Override the netmask sent to clients. Normally it is calculated from the </br>subnet that is served."        : "更新子网掩码.",
	"Override the table used for internal routes"        : "更新内部路由表",
	"Overview"        : "总览",
	"Owner"        : "用户名",
	"PAP/CHAP password"        : "密码",								
	"PAP/CHAP username"        : "用户名",
	"PID"        : "PID",
	"PIN"        : "PIN",
	"PPP"        : "PPP",
	"PPPoA Encapsulation"        : "PPPoA封包",
	"PPPoATM"        : "PPPoATM",
	"PPPoE"        : "PPPoE",
	"PPtP"        : "PPtP",
	"Package libiwinfo required!"        : "需要libiwinfo软件包!",
	"Package lists are older than 24 hours"        : "软件包列表已超过24小时未更新",
	"Package name"        : "软件包名称",
	"Packets"        : "数据包",
	"Part of zone %q"        : "区域 %q",
	"Password"        : "密  码",
	"Password authentication"        : "密码验证",
	"Password of Private Key"        : "私有密钥",
	"Password successfully changed!"        : "密码修改成功!",
	"Path to CA-Certificate"        : "CA证书路径",
	"Path to Client-Certificate"        : "客户端证书路径",
	"Path to Private Key"        : "私钥路径",
	"Path to executable which handles the button event"        : "处理按键动作的可执行文件路径",
	"Peak:"        : "峰值:",
	"Perform reset"        : "执行复位",
	"Phy Rate:"        : "物理速率:",
	"Physical Settings"        : "物理设置",
	"Ping"        : "Ping",
	"Pkts."        : "数据包",
	"Please enter your username and password."        : "请输入用户名和密码.",
	"Please wait: Device restore..."        : "设备重启中,以便恢复出厂配置,请等待",
	"Please wait: Device rebooting..."        : "设备重启中,请等待",
	"Please wait: Device restore config..."        : "设备重启中,以便配置恢复,请等待",
	"Policy"        : "策略",
	"Port %d"        : "端口 %d",
	"Port %d is untagged in multiple VLANs!"        : "端口 %d 在多个VLAN中均未关联!",
	"Port status:"        : "端口状态:",
	"Presume peer to be dead after given amount of LCP echo failures, use 0 to </br>ignore failures"        : "在指定数量的LCP响应故障后假定链路已断开,0为忽略故障",
	"Prevents client-to-client communication"        : "禁止客户端间通信",
	"Prism2/2.5/3 802.11b Wireless Controller"        : "Prism2/2.5/3 802.11b 无线网卡",
	"Proceed"        : "执行",
	"Processes"        : "系统进程",
	"Prot."        : "协议",
	"Protocol"        : "协议",
	"Protocol family"        : "协议族",
	"Protocol of the new interface"        : "新接口的协议",
	"Protocol support is not installed"        : "未安装协议支持",
	"Provide NTP server"        : "NTP服务器",
	"Provide new network"        : "添加新网络",
	"Pseudo Ad-Hoc (ahdemo)"        : "伪装Ad-Hoc(ahdemo)",
	"Public prefix routed to this device for distribution to clients."        : "",
	"Quality"        : "质量",
	"RTS/CTS Threshold"        : "RTS/CTS阈值",
	"RX"        : "接收",
	"RX Rate"        : "接收速率",
	"RaLink 802.11%s Wireless Controller"        : "MediaTek/RaLink 802.11%s 无线网卡",
	"Radius-Accounting-Port"        : "Radius 计费端口",
	"Radius-Accounting-Secret"        : "Radius 计费密钥",
	"Radius-Accounting-Server"        : "Radius 计费服务器",
	"Radius-Authentication-Port"        : "Radius 认证端口",
	"Radius-Authentication-Secret"        : "Radius 认证密钥",
	"Radius-Authentication-Server"        : "Radius 认证服务器",
	"Really reset all changes?"        : "确定要放弃所有更改?",
	"Really switch protocol?"        : "确定要切换协议?",
	"Realtime Connections"        : "实时连接",
	"Realtime Graphs"        : "实时信息",
	"Realtime Load"        : "实时负载",
	"Realtime Traffic"        : "实时流量",
	"Realtime Monitor"        : "实时流量",
	"Realtime Wireless"        : "实时无线",
	"Rebind protection"        : "重绑定保护",
	"Reboot"        : "重启",
	"Rebooting..."        : "重启中...",
	"Reboots the operating system of your device"        : "重启OpenWrt",
	"Receive"        : "接收",
	"Receiver Antenna"        : "接收天线",
	"Reconnect this interface"        : "重连此接口",
	"Reconnecting interface"        : "重连接口中...",
	"References"        : "引用",
	"Regulatory Domain"        : "无线网络国家区域",
	"Relay"        : "中继",
	"Relay Bridge"        : "中继桥",
	"Relay between networks"        : "网络间中继",
	"Relay bridge"        : "中继桥",
	"Remote IPv4 address"        : "远程IPv4地址",
	"Remove"        : "移除",
	"Repeat scan"        : "重新扫描",
	"Replace entry"        : "重置条目",
	"Replace wireless configuration"        : "重置无线配置",
	"Request IPv6-address"        : "请求IPv6地址",
	"Request IPv6-prefix of length"        : "",
	"Required for certain ISPs, e.g. Charter with DOCSIS 3"        : "某些ISP需要,例如:同轴线网络DOCSIS 3",
	"Reset"        : "复位",
	"Reset Counters"        : "复位计数器",
	"Reset to defaults"        : "恢复到出厂设置",
	"Resolv and Hosts Files"        : "HOSTS和解析文件",
	"Resolve file"        : "解析文件",
	"Restart"        : "重启",
	"Restart Firewall"        : "重启防火墙",
	"Restore backup"        : "恢复配置",
	"Restore"        : "恢复配置",
	"Reveal/hide password"        : "显示/隐藏 密码",
	"Revert"        : "放弃",
	"Root"        : "Root",
	"Root directory for files served via TFTP"        : "TFTP服务器的根目录",
	"Router Advertisement-Service"        : "",
	"Router Password"        : "主机密码",
	"Routes"        : "路由表",
	"Routes specify over which interface and gateway a certain host or network </br>can be reached."        : "路由表描述了数据包的可达路径.",
	"Rule #"        : "规则 #",
	"Run a filesystem check before mounting the device"        : "挂载设备前运行文件系统检查",
	"Run filesystem check"        : "文件系统检查",
	"SSH Access"        : "SSH访问",
	"SSH-Keys"        : "SSH-密钥",
	"SSID"        : "SSID",
	"Save"        : "保存",
	"Save & Apply"        : "保存&应用",
	"Save &#38; Apply"        : "保存&#38;应用",
	"Scan"        : "搜索",
	"Scheduled Tasks"        : "计划任务",
	"Section added"        : "添加的区域",
	"Section removed"        : "移除的区域",
	"Send LCP echo requests at the given interval in seconds, only effective in </br>conjunction with failure threshold"        : "定时发送LCP响应(秒),仅在结合了故障阈值时有效",
	"Separate Clients"        : "无线客户端隔离",
	"Separate WDS"        : "隔离WDS",
	"Server Settings"        : "服务器设置",
	"Service Name"        : "服务名",
	"Service Type"        : "服务类型",
	"Services"        : "服务",
	"Set up Time Synchronization"        : "设置时间同步",
	"Setup DHCP Server"        : "配置DHCP服务器",
	"Show current backup file list"        : "显示当前文件备份列表",
	"Shutdown this interface"        : "关闭此接口",
	"Shutdown this network"        : "关闭此网络",
	"Signal"        : "信号",
	"Signal:"        : "信号:",
	"Size"        : "大小",
	"Skip"        : "跳过",
	"Skip to content"        : "跳到内容",
	"Skip to navigation"        : "跳转到导航",
	"Slot time"        : "时隙",
	"Software"        : "软件包",
	"Some fields are invalid, cannot save values!"        : "一些项目的值无效,无法保存!",
	"Sorry, the object you requested was not found."        : "对不起,请求的目标未找到.",
	"Sorry, the server encountered an unexpected error."        : "对不起,服务器遇到未知错误.",
	"Sorry, there is no sysupgrade support present; a new firmware image must be </br>flashed manually. Please refer to the OpenWrt wiki for device specific </br>install instructions."        : "抱歉,当前系统不支持sysupgrade升级,需手动刷新固件.请参考OpenWrt Wiki中此设 </br>备特定的安装向导.",
	"Sort"        : "排序",
	"Source"        : "源地址",
	"Specifies the button state to handle"        : "指定要处理的按键状态",
	"Specifies the directory the device is attached to"        : "指定设备的挂载目录",
	"Specifies the listening port of this <em>Dropbear</em> instance"        : "指定<em>Dropbear</em>的监听端口",
	"Specifies the maximum amount of failed ARP requests until hosts are presumed to be dead"        : "指定假设主机已丢失的最大失败ARP请求数",
	"Specifies the maximum amount of seconds after which hosts are presumed to be dead"        : "指定假设主机已丢失的最大时间(秒)",
	"Specify the secret encryption key here."        : "在此指定密钥.",
	"Start"        : "开始",
	"Start priority"        : "启动优先级",
	"Startup"        : "启动项",
	"Static IPv4 Routes"        : "静态IPv4路由",
	"Static IPv6 Routes"        : "静态IPv6路由",
	"Static Leases"        : "静态地址分配",
	"Static Routes"        : "静态路由",
	"Static WDS"        : "静态WDS",
	"Static address"        : "静态地址",
	"Static leases are used to assign fixed IP addresses and symbolic hostnames </br>to DHCP clients. They are also required for non-dynamic interface </br>configurations where only hosts with a corresponding lease are served.</br>"        : "静态租约用于给DHCP客户端分配固定的IP地址和主机标识.只有指定的主机才能连接,</br>并且接口须为非动态配置.",
	"Status"        : "状态",
	"Stop"        : "停止",
	"Strict order"        : "严谨查序",
	"Swap"        : "交换区",
	"Swap Entry"        : "交换项目",
	"Switch"        : "开关",
	"Switch %q"        : "交换机 %q",
	"Switch %q (%s)"        : "交换机%q (%s)",
	"Switch protocol"        : "切换协议",
	"Sync with browser"        : "同步浏览器时间",
	"Synchronizing..."        : "同步中...",
	"System"        : "系统",
	"System Log"        : "系统日志",
	"System Properties"        : "系统属性",
	"System log buffer size"        : "系统日志缓冲区大小",
	"TCP:"        : "TCP:",
	"TFTP Settings"        : "TFTP设置",

	"TFTP server root"        : "TFTP服务器根目录",
	"TX"        : "发送",
	"TX Rate"        : "发送速率",
	"Table"        : "表",
	"Target"        : "对象",
	"Terminate"        : "关闭",
	"The flash image was uploaded. Below is the checksum and file size listed, compare them with the original file to ensure data integrity.<br /> Click \"Proceed\" below to start the flash procedure."        : "固件已上传,请注意核对文件大小和校验值!<br />刷新过程切勿断电!",
	"The following changes have been committed"        : "以下更改已提交",
	"The following changes have been reverted"        : "以下更改已放弃",
	"The following rules are currently active on this system."        : "系统中的活跃连接.",
	"The given network name is not unique"        : "给定的网络名重复",
	"The system is flashing now.<br /> DO NOT POWER OFF THE DEVICE!Wait a </br>few minutes before you try to reconnect. It might be necessary to renew the </br>address of your computer to reach the device again, depending on your </br>settings."        : "正在刷新系统...<br />切勿关闭电源! DO NOT POWER OFF THE DEVICE!<br />稍等数分</br>钟即可重新连接到路由.可能需要更改计算机的IP地址以重新连接.",
	"The uploaded image file does not contain a supported format. Make sure that </br>you choose the generic image format for your platform."        : "不支持所上传的文件格式.请确认选择的文件无误.",
	"There are no active leases."        : "没有已分配的租约.",
	"There are no pending changes to apply!"        : "没有待生效的更改!",
	"There are no pending changes to revert!"        : "没有可放弃的更改!",
	"There are no pending changes!"        : "没有待生效的更改!",
	"This IPv4 address of the relay"        : "中继的IPv4地址",
	"This is the plain username for logging into the account"        : "登录账户时填写的用户名",
	"This is the system crontab in which scheduled tasks can be defined."        : "自定义系统crontab中的计划任务.",
	"This page allows the configuration of custom button actions"        : "自定义按键动作.",
	"This page gives an overview over currently active network connections."        : "活跃的网络连接概况.",
	"This section contains no values yet"        : "尚无任何配置",
	"Time Synchronization"        : "时间同步",
	"Time Synchronization is not configured yet."        : "尚未配置时间同步",
	"Timezone"        : "时区",
	"Total Available"        : "可用数",
	"Traceroute"        : "Traceroute",
	"Traffic"        : "流量",
	"Transfer"        : "传输",
	"Transmission Rate"        : "传送速率",
	"Transmit"        : "传送",
	"Transmit Power"        : "无线发射功率",
	"Transmitter Antenna"        : "传送天线",
	"Trigger"        : "触发",
	"Trigger Mode"        : "触发模式",
	"Tunnel ID"        : "隧道ID",
	"Tunnel Interface"        : "隧道接口",
	"Tunnel Link"        : "",
	"Turbo Mode"        : "Turbo模式",
	"Tx-Power"        : "传输功率",
	"Type"        : "类型",
	"UDP:"        : "UDP:",
	"UMTS only"        : "仅UMTS(WCDMA)",
	"UMTS/GPRS/EV-DO"        : "UMTS/GPRS/EV-DO",
	"USB Device"        : "USB设备",
	"UUID"        : "UUID",
	"Unable to dispatch"        : "无法调度",
	"Unknown"        : "未知",
	"Unknown Error, password not changed!"        : "未知错误,密码未更改!",
	"Unmanaged"        : "桥接",
	"Unsaved Changes"        : "未保存的配置",
	"Unsupported protocol type."        : "不支持的协议类型",
	"Update lists"        : "刷新列表",
	"Upload a sysupgrade-compatible image here to replace the running firmware. </br>Check \"Keep settings\" to retain the current configuration (requires an </br>OpenWrt compatible firmware image)."        : "上传兼容的sysupgrade固件以刷新当前系统.",
	"Upload archive..."        : "上传备份...",
	"Uploaded File"        : "上传的文件",
	"Uptime"        : "运行时间",
	"Use DHCP gateway"        : "使用DHCP网关",
	"Use DNS servers advertised by peer"        : "使用端局通告的DNS服务器",
	"Use ISO/IEC 3166 alpha2 country codes."        : "参考ISO/IEC 3166 alpha2国家代码.",
	"Use MTU on tunnel interface"        : "隧道接口的MTU",
	"Use TTL on tunnel interface"        : "隧道接口的TTL",
	"Use broadcast flag"        : "使用广播标签",
	"Use builtin IPv6-management"        : "",
	"Use custom DNS servers"        : "使用自定义的DNS服务器",
	"Use default gateway"        : "使用默认网关",
	"Use gateway metric"        : "使用网关跃点",
	"Use routing table"        : "使用路由表",
	"Used"        : "已用",
	"Used Key Slot"        : "启用密码组",
	"Username"        : "用户名",
	"VC-Mux"        : "VC-Mux",
	"VLAN Interface"        : "VLAN接口",
	"VLANs on %q"        : "%q上的VLAN",
	"VLANs on %q (%s)"        : "%q (%s)上的VLAN",
	"VPN Server"        : "VPN服务器",
	"Vendor Class to send when requesting DHCP"        : "请求DHCP时发送的Vendor Class",
	"Verify"        : "验证",
	"Version"        : "版本",
	"WDS"        : "WDS",
	"WEP Open System"        : "WEP开放认证",
	"WEP Shared Key"        : "WEP共享密钥",
	"WEP passphrase"        : "WEP密钥",
	"WMM Mode"        : "WMM多媒体加速",
	"WPA passphrase"        : "WPA密钥",
	"Waiting for changes to be applied..."        : "正在应用更改...",
	"Waiting for command to complete..."        : "正在执行命令...",
	"warning"        : "警告",
	"Warning: There are unsaved changes that will be lost while rebooting!"        : "警告: 有尚未保存的更改,重启将丢失!",
	"Wifi"        : "无线",
	"WiFi Info"		:"WiFi信息",
	"Wireless"        : "无线",
	"Wireless Adapter"        : "无线适配器",
	"Wireless Network"        : "无线网络",
	"Wireless Overview"        : "无线概况",
	"Wireless Security"        : "无线安全",
	"Wireless is disabled or not associated"        : "未开启或未关联无线",
	"Wireless is restarting..."        : "重启无线中...",
	"Wireless network is disabled"        : "无线已禁用",
	"Wireless network is enabled"        : "无线网络开关",
	"Wireless restarted"        : "无线已重启",
	"Wireless shut down"        : "无线已关闭",
	"Write received DNS requests to syslog"        : "将收到的DNS请求写入系统日志",
	"XR Support"        : "XR支持",
	"any"        : "任意",
	"auto"        : "自动",
	"automatic"        : "自动",
	"baseT"        : "baseT",
	"bridged"        : "桥接的",
	"create:"        : "创建:",
	"creates a bridge over specified interface(s)"        : "为指定接口创建桥接",
	"dB"        : "dB",
	"dBm"        : "dBm",
	"disable"        : "禁用",
	"disabled"        : "已禁用",
	"expired"        : "过期时间",
	"forward"        : "转发",
	"full-duplex"        : "全双工",
	"half-duplex"        : "半双工",
	"help"        : "帮助",
	"hidden"        : "隐藏",
	"hybrid mode"        : "混合模式",
	"if target is a network"        : "如果对象是一个网络",
	"input"        : "输入",
	"kB"        : "kB",
	"kB/s"        : "kB/s",
	"kbit/s"        : "kbit/s",
	"no"        : "no",
	"no link"        : "未连接",
	"none"        : "无",
	"off"        : "关",
	"on"        : "开",
	"open"        : "开放式",
	"overlay"        : "",
	"relay mode"        : "中继模式",
	"routed"        : "已路由",
	"server mode"        : "服务器模式",
	"stateful-only"        : "",
	"stateless"        : "",
	"stateless + stateful"        : "",
	"tagged"        : "关联",
	"unknown"        : "未知",
	"unlimited"        : "无限制",
	"unspecified"        : "未指定",
	"unspecified -or- create:"        : "未指定 // 创建:",
	"untagged"        : "不关联",
	"yes"        : "是",
	"? Back"        : "? 后退",
	"Detailed rules for firewall settings"        : "防火墙设置详细规则",
	"Inhibit port scan:"        : "抑制端口扫描:",
	"Inhibition of IP deception:"        : "抑制IP欺骗:",
	"Ban WAN Ping:"        : "禁止wan口Ping:",
	"Anti SYN flooding:"        : "防syn泛洪:",
	"Anti fragment attack:"        : "防碎片攻击:",
	"Prevent death of Ping:"        : "防死亡之ping:",
	"Anti Netbios sniffer:"        : "防Netbios嗅探:",
	"Tcpsvcs intrusion prevention:"        : "防tcpsvcs入侵:",
	"Anti null TCP scan:"        : "防tcp null扫描:",
	"Anti smurf attack:"        : "防smurf攻击:",
	"Anti snork attack:"        : "防snork攻击:",
	"Anti land attack:"        : "防land攻击:",
	"Anti Slammer virus:"        : "防slammer病毒:",
	"Anti hack-a-tack virus:"        : "防hack-a-tack病毒:",
	"Anti NetSphere virus:"        : "防NetSphere病毒:",
	"Anti Sasser virus:"        : "防Sasser病毒:",
	"Software Version"        : "软件版本",
	"Bind Port"        : "绑定端口",
	"Bind SSID"        : "绑定SSID",
	"Reboot device"        : "重启设备",
	"Hardware Version"        : "硬件版本",
	"Serial Number"        : "序列号",
	"VLan has been used,please replace the Vlan"        : "Vlan已被使用,请更换Vlan",
	"Shutdown"        : "断开",
	"Channel 12 and 13 are chinese standard,maybe make some device don't link"        : "信道12和13 是中国标准,可能导致一些设备无法连接",
	"Channel 12 and 13 are chinese standard,Country must be choose CN-China"        : "信道12和13是中国标准,国家代码必须选择CN-China",
	"Port has been used,please replace the binding port"        : "端口已经使用,请更换绑定端口",
	"must bind one port at least"        : "必须绑定至少一个端口",
	"Limit number of Connected client, 0 is no limit,max is 64"        : "SSID客户端连接个数,0不限制,最大限制64",
	"Limit number of Connected client, 0 is no limit,max is 32"        : "SSID客户端连接个数,0不限制,最大限制32",
	"Limit number must be between 0 and 64"        : "连接限制个数有效范围0~64",
	"Vlan error,please replace the Vlan"        : "Vlan值错误,请更换Vlan值",
	"General Info"        : "基本信息",
	"Wireless client list"        : "无线客户端列表",
	"CHENGDU KINGTYPE (ELECTRONIC) GROUP CO.All Rights Reserved"        : "成都康特电子高新科技有限责任公司",
	"Click \"Generate archive\" to download a tar archive of the current </br>configuration files. To reset the firmware to its initial state, click </br>\"Perform reset\""        : "备份/恢复当前系统配置文件或重置设备",
	"English"        : "英文",
	"Login Password"        : "登录密码",
	"Login Account"        : "登录用户名",
	"Password can not be empty!"        : "密码不能为空!",
	"Super User Password"        : "超级用户密码",
	"General User Password"        : "普通用户密码",
	"Changes the super user password for accessing the device"        : "修改访问设备的超级用户密码",
	"Changes the general user password for accessing the device"        : "修改访问设备的普通用户密码",
	"LAN Config"        : "LAN配置",
	"WAN Config"        : "WAN配置",
	"On this page you can configure the LAN interfaces."        : "可配置LAN接口的各种参数",
	"On this page you can configure the network interfaces."        : "可配置路由接口的各种参数",
	"DHCP Settings"        : "DHCP 配置",
	"Expiry time of leased addresses, minimum is 2 minutes,maximum is 1440 minutes.The unit is minutes."        : "地址租期,最短时间2分钟,最长时间1440分钟,单位是分钟.",
	"Expiry time of leased addresses, minimum is 2 minutes,maximum is 1440 minutes."        : "地址租期,最短时间2分钟,最长时间1440分钟.",
	"RF Settings"        : "射频配置",
	"WIFI"        : "无线",
	"WIFI Config"        : "无线配置",
	"Really shutdown interface"        : "确定要关闭接口",
	"You might lose access to this device if you are connected via this interface."        : "删除此接口,可能导致无法连接路由器!",
	"Really shut down network?"        : "确定要关闭此网络?",
	"You might lose access to this device if you are connected via this network."        : "删除此网络,可能导致无法连接路由器!",
	"ssid max length is 32"        : "SSID 长度最大32",
	"Max length is 32."        : "最大长度32.",
	"Max length is 64."        : "最大长度64.",
	"ssid error."        : "SSID错误,不允许包含特殊字符",
	"Chinese"        : "中文",
	"Hide SSID"        : "隐藏SSID",
	"number of leased addresses error."        : "客户数错误,最小数目为1",
	"Leasetime error."        : "租期时间错误",
	"error code"        : "错误代码",
	"Isolate Clients"        : "SSID的用户隔离",
	"Client Limit"        : "SSID最大连接数",
	"SSID cannot be empty!"        : "SSID 不能为空!",
	"SSID err, invalied character"					:"SSID 有无效字符",
	"Chinese SSID less than or equal 10 character"	:"中文SSID应小于等于10个中文字符.",
	"Cannot end with a null character"				:"SSID 不能以空字符结束.",
	"Management WAN"        : "管理WAN",
	"Service WAN"        : "业务WAN",
	"Management Channel"        : "管理通道",
	"Modify access device management channel properties."        : "修改访问设备的管理通道属性",
	"Waiting for changes to be applied,the device will automatically restart."        : "正在应用更改,设备将自动重启.",
	"Restore config success and will auto reboot device!"        : "恢复配置成功,设备将自动重启!",
	"ACS Server"        : "ACS服务器",
	"CPE Authentication Enable"        : "CPE认证使能",
	"CPE Authentication Account"        : "CPE认证账号",
	"CPE Authentication Password"        : "CPE认证密码",
	"CPE Connection Authentication Enable"        : "CPE连接认证使能",
	"CPE Connection Authentication Account"        : "CPE连接认证账号",
	"CPE Connection Authentication Password"        : "CPE连接认证密码",
	"The ACS server address length 1 to 64."        : "ACS服务器地址长度1到64.",
	"User name length ranges from 1 to 32."        : "用户名长度范围是1到32.",
	"Password length ranges from 1 to 32."        : "密码长度范围是1到32.",
	"Management VALN ranges from 1 to 4095."        : "管理VLAN值范围是1到4095.",
	"Polling Time(unit seconds)"        : "轮询时间(单位秒)",
	"Inform interval ranges from 30 to 3600."        : "轮询时间范围是30到3600秒.",
	"Network Quick Config"        : "快速配置",
	"On this page you can configure the network interfaces quickly."        : "可快速配置路由接口的各种参数.",
	"SSID Config"        : "SSID 配置",
	"Port has been used,force bind port"        : "端口已经使用,是否直接绑定",
	"Quick Config"        : "快速配置",
	"Forwarding rules"        : "转发规则",
	"DMZ Host"        : "DMZ主机",
	"DMZ Host IP Address"        : "DMZ 主机IP地址",
	"In some special cases, we need to let a computer local area network completely exposed to the wide area network, in order to achieve two-way communication, then the computer can be set to the DMZ host.When the DMZ host IP address is empty, DMZ status is disabled."        : "在某些特殊情况下,需要让局域网中的一台计算机完全暴露给广域网,以实现双向通信,此时可以把该计算机设置为DMZ主机.当DMZ主机IP地址为空时,DMZ状态为禁用.",
	"Port Forwarding"        : "端口转发",
	"Service Port"        : "服务端口",
	"DNS Proxy"        : "代理DNS",
	"The upgrade file cannot be more than"        : "升级文件不能超过",
	"The file cannot be more than"        : "文件不能超过",
	"IP address cannot be empty!"        : "IP地址不能为空!",
	"IP address and LAN IP not in the segment!"        : "IP地址和LAN IP不在同一个网段!",
	"IP address and LAN IP not in the segment,Pleaes re-enter!"        : "IP地址和LAN IP不在同一个网段,请重新输入!",
	"IP address format error!"        : "IP地址格式错误!",
	"Port number repeat!"        : "端口号重复!",
	"Port number cannot be empty!"        : "端口号不能为空!",
	"Quick config fixed support WPA-PSK/WPA2-PSK Mixed Mode."        : "快速配置固定支持WPA-PSK/WPA2-PSK Mixed Mode.",
	"The current encryption mode is WEP Open System."        : "当前加密模式是WEP开放认证.",
	"The current encryption mode is WEP Shared Key."        : "当前加密模式是WEP共享密钥.",
	"Port is used, will be rebinding!"        : "端口被占用,已重新绑定!",
	"One of mac address must be specified!"        : "请指定MAC地址!",
	"Original Password"        : "当前密码",
	"New Password"        : "新密码",
	"The new password is not consistent with the two,please re-enter"        : "新密码两次输入不一致,请重新输入",
	"Original Password input error"        : "原密码输入错误",
	"PasswordFmtTips"						:"新密码必须含数字、字母和特殊字符三种",
	"PasswordLenTips"							:"新密码长度不能小于8位或者大于31位 !",
	"CurrPwdInvalid"		:"当前登录密码错误!",
	"super_user modify tips"		:"超级用户名不支持修改!",
	"super_pwd modify tips"		:"超级账号密码不支持修改!",
	"PwdGotoIndex"					:"密码修改成功,将跳转到登录页面!",
	"UserGotoIndex"					:"用户名修改成功,将跳转到登录页面!",
	"Main DNS Server"        : "主DNS服务器",
	"Alternate DNS Server"        : "备DNS服务器",
	"IPv6 Main DNS Server"        : "IPv6主DNS服务器",
	"IPv6 Alternate DNS Server"        : "IPv6备DNS服务器",
	"Wireless Switch"        : "无线开关",
	"WI-FI Switch"        : "WiFi开关",
	"DHCP Enable"        : "DHCP开关",
	"Start IP"        : "起始IP",
	"End IP"        : "结束IP",
	"IP Range"		:"IP分配范围",
	"Start ip error,please re-enter"        : "起始IP错误,请重新输入",
	"End ip error,please re-enter"        : "结束IP错误,请重新输入",
	"Network end distribution address(10~252)."        : "网络结束分配地址(10~252).",
	"Network end distribution address(10~253)."        : "网络结束分配地址(10~253).",
	"Management Channel Enable"        : "管理通道使能",
	"Running State"        : "运行状态",
	"Device Information"        : "设备信息",
	"activated"        : "已启用",
	"Upstream"        : "上行",
	"Down"        : "下行",
	"UpLimit"        : "上行限速",
	"DownLimit"        : "下行限速",	
	"Dnsmasq is a combined DHCP-Server and DNS-Forwarder for NAT firewalls."        : "为NAT防火墙提供了一个集成的DHCP服务器和DNS转发器.",
	"Device Management"        : "设备管理",
	"Reset router to defaults"        : "恢复出厂设置",
	"Reset successfully router to defaults"        : "恢复出厂设置成功",
	"Clicking this button will allow the system to restore all settings to factory default setting."        : "单击此按钮将使系统的所有设置恢复到出厂时的默认状态.",
	"Firmware Update"        : "升级固件",
	"Safe"        : "安全",
	"Virtual Server"        : "虚拟服务器",
	"Virtual Server allows remote computers on the Internet to connect to a specific computer or service within the private LAN."        : "虚拟服务器允许来自Internet的计算机访问私有局域网内的计算机或服务.",
	"Time Management"        : "时间管理",
	"Log Management"        : "日志管理",
	"User Management"        : "用户管理",
	"Changes the user password for accessing the device"        : "修改访问设备的用户密码",
	"The new password is the same as the original password,please re-enter"        : "新密码与原密码相同,请重新输入",
	"Vlan has been used,please replace the Vlan"        : "该vlan已经被使用,请重新输入",
	"MAC address cannot be empty!"        : "MAC地址不能为空!",
	"MAC address was occupied,please input again!"        : "MAC地址被占用,请重新输入!",
	"IP address was occupied,please input again!"        : "IP地址被占用,请重新输入!",
	"Wireshark Test"        : "抓包测试",
	"Start wireshark"        : "开始抓包",
	"Wiresharking..."        : "正在抓包...",
	"Wireshark commond:"        : "抓包命令:",
	"Download"        : "下载",
	"Download wireshark"        : "下载抓包",
	"Please wait: Wiresharking..."        : "请稍等,抓包中...",
	"Stop wireshark and download"        : "停止抓包并下载",
	"Stop wireshark"        : "停止抓包",
	"Run status"        : "运行状态",
	"Network info"        : "网络信息",
	"User info"        : "用户信息",
	"Device info"        : "设备信息",
	"IPV4 connect info"        : "IPV4连接信息",
	"EOC connect info"        : "EOC连接信息",
	"Wlan info"        : "Wlan信息",
	"Lan info"        : "Lan信息",
	"System Time"				:"系统日期时间",
	"Time Zone"					:"时间区域",
	"Timeout management"        : "超时管理",
	"Primary SNTP server"		:"主SNTP服务器",
	"From SNTP server"			:"从SNTP服务器",
	"Timeout time"        : "超时时间",
	"1 min"        : "1分钟",
	"2 min"        : "2分钟",
	"5 min"        : "5分钟",
	"10 min"        : "10分钟",
	"15 min"        : "15分钟",
	"30 min"        : "30分钟",
	"1 hour"        : "1小时",
	"Application"        : "应用",
	"DDNS Config"        : "DDNS配置",
	"Advanced NAT Config"        : "高级NAT配置",
	"IGMP Config"        : "IGMP配置",
	"DDNS Enable"        : "DDNS使能",
	"Service Providers"        : "服务商",
	"Domain Name"        : "域名",
	"Packet Filter"        : "数据包过滤",
	"Wan access control"        : "Wan侧访问控制",
	"Storm Inhibit"        : "风暴抑制",
	"SSID config overview"        : "SSID 配置总览",
	"Clicking this button will reboot system."        : "单击此按钮将重启设备.",
	"Download syslog"        : "日志下载",
	"WAN config overview"        : "WAN配置总览",
	"Wireless Switch Time"        : "无线定时开关",
	"Ranges"        : "范围",
	"Hour"        : "小时",
	"Open Time"        : "开启时间",
	"Close Time"        : "关闭时间",
	"Miniute"        : "分钟",
	"disable&enable"        : "是否开启",
	"Everyday"        : "每天",
	"Monday"        : "星期一",
	"Tuesday"        : "星期二",
	"Wednesday"        : "星期三",
	"Thursday"        : "星期四",
	"Friday"        : "星期五",
	"Saturday"        : "星期六",
	"Sunday"        : "星期天",
	"Please enter wireshark command:"        : "请输入抓包命令:",
	"Notice: Stop wireshark you can download result"        : "注:停止抓包后你可以下载抓包结果",
	"Access Whitelist"        : "访问白名单",
	"Add whitelist"        : "添加白名单",
	"Remove whitelist"        : "移除白名单",
	"Add blacklist"        : "添加黑名单",
	"Remove blacklist"        : "移除黑名单",
	"Access Control"        : "访问控制",
	"Policy type"        : "调度策略",
	"Weight"        : "权重",
	"Uplink bandwidth"        : "上行带宽",
	"Queue"        : "队列",
	"Business name"        : "业务名称",
	"Multicat packet threshold"        : "组播包门限值",
	"Broadcast packet threshold"        : "广播包门限值",
	"Clicking this button will download all setting."        : "单击此按钮将使系统的所有设置下载到本地.",
	"Upload local config to restore config"        : "上传本地配置文件",
	"Mac Filter"        : "MAC 过滤",
	"IP Filter"        : "IP 过滤",
	"PROTO Filter"        : "PROTO 过滤",
	"EOC Connect Info"        : "EOC连接信息",
	"EOC Slave MAC"        : "EOC终端MAC",
	"EOC Master MAC"        : "EOC局端MAC",
	"EOC Up Bindwidth"        : "EOC上行物理带宽",
	"EOC Down Bindwidth"        : "EOC下行物理带宽",
	"EOC Up Noise"        : "EOC上行信噪比",
	"EOC Down Noise"        : "EOC下行信噪比",
	"Eoc not connect!"        : "获取EOC失败!",
	"Backup config"        : "配置备份",
	"Backup"        : "配置备份",
	"Rstore backup config"        : "导入配置文件",
	"DMZ SET"        : "DMZ设置",
	"Dest-host"        : "目标主机",
	"Notice: This Function will work at the next login or reboot!"        : "提示:该功能将在下一次登录或重启后生效!",
	"0 is no limit"        : "0不限制",
	"0 is no limit,max is 62500"        : "0不限制,最大限制62500",
	"RX Limit"        : "上行限速",
	"Save & Apply success"        : "保存&应用 成功",
	"Dest-host cannot be empty!"        : "目标主机不能为空!",
	"Netmask is not match with this IP address,Pleaes re-enter!"        : "子网掩码与IP地址不匹配,请重新输入!",
	"Browser version is too low ,Please use IE9 or more to view!"        : "浏览器版本过低,请使用IE9及以上版本查看!",
	"The min is 128"        : "最小值128",
	"Please choice file!"        : "请选择文件!",
	"Restore config success!"        : "恢复配置成功",
	"Restore config failed,please re-choice config file!"        : "恢复配置失败,请重新选择文件!",
	"The host ip limit"        : "主机地址不能小于10或者大于252!",
	"The end ip connot lower start ip!"        : "结束IP不能小于开始IP!",
	"Vendor id"        : "厂商 ID",
	"UPnP settings"        : "UPnP设置",
	"UPnP listening port"        : "UPnP监听端口",
	"ACLs specify which external ports may be redirected to which internal </br>addresses and ports"        : "指定外部端口的ACL可能会被重定向至某些内部地址及端口",
	"Active UPnP Redirects"        : "活动的UPnP重定向",
	"Advanced Settings"        : "高级设置",
	"Allow adding forwards only to requesting ip addresses"        : "允许添加只转发给请求的IP地址(当启用时,UPnP的客户可以只转发到其IP)",
	"Announced model number"        : "公布的型号",
	"Announced serial number"        : "公布的序列号",
	"Clean rules interval"        : "定时自动清除无效规则",
	"Clean rules threshold"        : "启动时清除端口转发",
	"Client Address"        : "客户端地址",
	"Client Port"        : "客户端端口",
	"Comment"        : "备注",
	"Delete Redirect"        : "删除转发规则",
	"Device UUID"        : "设备UUID",
	"Downlink"        : "下行速率",
	"Enable NAT-PMP functionality"        : "启用NAT-PMP功能",
	"Enable UPnP functionality"        : "启用UPnP功能",
	"Enable additional logging"        : "启用额外的日志记录",
	"Enable secure mode"        : "启用安全模式",
	"External Port"        : "外部端口",
	"External ports"        : "外部端口",
	"Internal addresses"        : "内网IP地址",
	"Internal ports"        : "内部端口",
	"MiniUPnP ACLs"        : "MiniUPnP的ACL",
	"MiniUPnP settings"        : "MiniUPnP设置",
	"Notify interval"        : "警报间隔",
	"Port"        : "端口",
	"Presentation URL"        : "显示URL",
	"Puts extra debugging information into the system log"        : "提取额外的调试信息至系统日志",
	"Report system instead of daemon uptime"        : "用系统运行时间代替进程运行时间",
	"Start UPnP and NAT-PMP service"        : "启动UPnP与NAT-PMP服务",
	"There are no active redirects."        : "没有活动的重定向",
	"UPNP"        : "UPNP",
	"UPnP allows clients in the local network to automatically configure the </br>router."        : "UPnP允许局域网内客户端自动设置路由上的端口转发.",
	"UPnP lease file"        : "UPnP租约文件",
	"Universal Plug & Play"        : "通用即插即用(UPnP)",
	"Uplink"        : "上行速率",
	"Value in KByte/s, informational only"        : "值为KByte/s,仅供参考",
	"Error number"        : "错误码",
	"Get IP address failed"        : "获取IP地址失败",
	"Firmware Update Success"        : "固件升级成功",
	"Uploading..."        : "正在上传...",
	"The ping function in access control does not apply to access the ping function in a whitelist"        : "访问控制中的ping功能不适用于访问白名单的ping功能",
	"Only support numbers, letters, _ and -"        : "仅支持数字、字母、中划线和下划线",
	"Only support numbers, letters, _ , - and #"        : "仅支持数字、字母、中划线、下划线和#",
	"Clear syslog"        : "清空日志",
	"Clear"        : "清空",
	"The wireless master switch is not on"        : "无线总开关未开启",
	"Some fields are invalid, Pleaes re-enter!"        : "一些项目的值无效,请重新输入!",
	"Family Network"        : "家庭网络",
	"Handware"        : "硬件",
	"Damping"        : "衰减",
	"Modulated Information"        : "调制信息",
	"Realtime Modulated Information"        : "实时调制信息",
	"Current device"        : "当前设备",
	"Welcome"        : "欢迎你",
	"Smart home gateway"        : "智能家庭网关",
	"PLC Modem"        : "电力线适配器",
	"ICP 05002517@Copyright China Mobile Limited. All right reserved. Disclaimer"        : "京ICP备05002571号 @ 中国移动通信版权所有",
	"Not support"        : "不支持",
	"and"        : "和",
	"300M wall mounted AP"        : "300M入墙式AP",
	"Product Model"        : "产品型号",
	"Part of configuration will take effect after reboot!"        : "部分配置将在重启后生效!",
	"Original Username"        : "当前用户名",
	"New Username"        : "新用户名",
	"User Name Set"        : "用户名称设置",
	"Original Username input error"        : "原用户名输入错误",
	"User Password Set"        : "用户密码设置",
	"Username can not be empty!"        : "用户名称不能为空!",
	"The new username is the same as the original username,please re-enter"        : "新用户名和原用户名一致,请重新输入",
	"Wan connect type"        : "WAN连接类型",
	"Route and Bridge"        : "一桥一路由",
	"Bridge and Bridge"        : "双桥连接",
	"is fixed head, not modifiable."        : "是固定头部,不可修改.",
	"Only one bridge one routing mode is effective"        : "仅一桥一路由模式有效",
	"Offline"        : "离线",
	"Please try again after"        : "请等待",
	"after s" :"秒后,重新登录",
	"Only route mode is effective"        : "仅路由模式有效",
	"Guest WI-FI Switch"        : "访客WiFi开关",
	"DHCP Config"        : "DHCP配置",
	"Password length 8-32,and must contain letters,numbers and _-#"        : "密码长度8到32位,并且必须同时包含字母、数字和符号(_-#)三种.",
	"IP Mode"        : "IP 模式",
	"China Mobile JiangSu Branch Version 1.0"        : "中国移动江苏公司1.0版本",
	"Network Config"        : "网络配置",
	"HT mode"        : "频宽",
	"1200M wall mounted AP"        : "1200M入墙式AP",
	"Admin Name Set"        : "管理名称设置",
	"Admin Password Set"        : "管理密码设置",
	"Software upgrade"        : "软件升级",
	"Login User Setting"        : "登录用户设置",
	"Login Password Setting"        : "登录密码设置",
	"Super User Setting"        : "超级用户设置",
	"Super Password Setting"        : "超级密码设置",
	"Note"        : "注意",
	"Stop wireshark you can download result"        : "停止抓包后你可以下载抓包结果",
	"This Function will work at the next login or reboot!"        : "该功能将在下一次登录或重启后生效!",
	"System Status"        : "系统状态",
	"reboot"        : "重启",
	"Uploading"        : "上传中...",
	"Config"        : "修改",
	"Work mode"        : "工作模式",
	"Wireless Roam Switch"        : "无线漫游开关",
	"2.4G Wireless Roam Rssi"        : "2.4G漫游阈值",
	"5G Wireless Roam Rssi"        : "5G漫游阈值",
	"Gateless self config"        : "无网关自助配置",
	"Loading..."        : "加载中...",
	"2.4G Signal Strength"        : "2.4G 信号强度",
	"5G Signal Strength"        : "5G 信号强度",
	"Connection Time"        : "连接时间(s)",
	"Rate"        : "协商速率(Mbit/s)",
	"Andlink Status"        : "Andlink状态",
	"Andlink Version"        : "Andlink版本",
	"Andlink Mode"        : "Andlink模式",
	"ANDLINK Status"        : "ANDLINK状态",
	"ANDLINK Version"        : "ANDLINK版本",
	"ANDLINK Mode"        : "ANDLINK模式",
	"Running Status"        : "运行状态",
	"Heartbeats"        : "心跳次数",
	"Product ID"        : "产品ID",
	"Product Token"        : "产品Token",
	"Andlink Token"        : "Andlink Token",
	"Device ID"        : "设备ID",
	"Device Token"        : "设备Token",
	"Gateway Token"        : "网关Token",
	"Gateway Ipaddress"        : "网关IP地址",
	"Gateway Userinfo"        : "网关用户信息",
	"Province Ipaddress"        : "省平台IP地址",
	"Looking for a gateway..."        : "正在查找网关...",
	"In register..."        : "正在注册...",
	"On the Internet..."        : "正在上线...",
	"In control..."        : "管控中...",
	"Out of control..."        : "不受管控...",
	"Network Info"        : "网络信息",
	"RX packets"        : "接收包数",
	"RX errors"        : "接收错误数",
	"RX dropped"        : "接收丢包数",
	"RX bytes"        : "接收字节数(KB)",
	"TX packets"        : "发送包数",
	"TX errors"        : "发送错误数",
	"TX dropped"        : "发送丢包数",
	"TX bytes"        : "发送字节数(KB)",
	"ARP Info"        : "ARP信息",
	"Network Status"        : "网络状态",
	"Management IP"        : "管理IP",
	"DownLink Device"        : "下挂设备",
	"Hostname Type"        : "主机类型",
	"master"        : "近端",
	"slave"        : "远端",
	"Config Sync"        : "配置同步",
	"Cannot be changed to this user name"        : "无法修改为该用户名",
	"Master-Slave Sync Switch"        : "近远端同步",
	"Min length is 8"        : "最小长度为8",
	"combination"        : "组合",
	"5 or 13 ASCII char"        : "5或13位ASCII字符",
	"10 or 26 hexadecimal char"        : "10或26位16进制字符",
	"space"        : "空格",
	"Number"        : "序号",
	"Username successfully changed!"        : "用户名修改成功!",
	"Not support Chinese and Chinese symbol"        : "不支持中文及中文符号",
	"IP Bind"        : "IP绑定",
	"Proto Filter"        : "协议过滤",
	"Guest Network"        : "访客网络",
	"Some illegal operations will not be saved. Such as IP is out of DHCP Pool or Device Mac set repeat"        : "一些非法操作,将不会被保存,例如IP地址超出DHCP地址池范围,或者MAC地址重复设置",
	"Ledsw"        : "指示灯开关",
	"Open"        : "开启",
	"Close"        : "关闭",
	"Flood control network"        : "防蹭网",
	"Parental control"        : "家长控制",
	"One-button Examination"        : "一键体检",
	"One-button Examination Result List"        : "一键体检结果列表",
	"Device is Safe"        : "体检结束,设备正常",
	"Proto Type"        : "协议类型",
	"IP Address"        : "IP地址",
	"Network Is Ready"        : "网络连接状态",
	"Wireless Status"        : "无线状态",
	"Wireless Is Encrypt"        : "无线加密状态",
	"Andlink Runing Status"        : "Andlink运行状态",
	"Nodelink Runing Status"        : "Nodelink运行状态",
	"Telnet Open Status"        : "Telnet开启状态",
	"CPU Load Average"        : "CPU平均负载",
	"Memory Used Status"        : "内存使用状态",
	"Notice: When click Start the One-button Examination Result List will Shown below!"        : "提示:点击开始后,一键体检结果列表将会在下方显示!",
	"Runing"        : "运行中",
	"Stop Runing"        : "未运行",
	"Network connection is normal"        : "网络连接正常",
	"Network connection failed"        : "网络连接失败",
	"Parental Control"        : "家长控制",
	"Only 10 switch plans are supported"        : "仅支持10条开关计划",
	"After modifying the IP addr,Please use the new addr for access"        : "修改IP地址过后,请使用新IP地址进行访问",
	"Device Run Mode Config"        : "设备运行模式配置",
	"Run Mode"        : "运行模式",
	"Bridge Mode"        : "桥接",
	"Route Mode"        : "路由",
	"2.4G WI-FI Setting"		:"2.4GWiFi设置",
	"5G WI-FI Setting"		:"5GWiFi设置",
	"WI-FI SSID"		:"WiFi名称",
	"Encryption Way"	:"加密方式",
	"WI-FI Passwd"	:"WiFi密码",
	"Hide WIFI"		:"隐藏WiFi",
	"Key #1"	:"密码 #1",
	"Key #2"	:"密码 #2",
	"Key #3"	:"密码 #3",
	"Key #4"	:"密码 #4",
	"Min length is 8,Not support ` ' \" \ < > $ space and (&#)combination,Not support Chinese and Chinese symbol"			:"最小长度为8,不支持 ` ' \" \\ < > $ & # ! , /空格,不支持中文及中文符号",
	"Not support ` ' \" \ < > $ space and (&#)combination,Not support Chinese and Chinese symbol"			:"不支持 ` ' \" \\ < > $ & # ! , /空格,不支持中文及中文符号",
	"5 or 13 ASCII char/10 or 26 hexadecimal char"		:"5或13位ASCII字符/10或26位16进制字符,不支持 ` ' \" \\ < > $ & # ! % , /空格",
	"Working Mode Setting"		:"工作模式设定",
	"Current Proto"				:"当前上网方式",
	"Telnet"					:"Telnet",
	"Max length is 32,Not support ` ' \" \ < > $ space and (&#)combination"			:"最大长度为32,不支持 ` ' , \" \\ < > $ 空格和 (&#)组合",
	"SSID Switch"		:"SSID开关",
	"Range(1-10080)"	:"范围(1-10080 分钟)",
	"Range(10-252)"		:"范围(10-252)",
	"Signal Strength"	:"信号强度(dBm)",
	"Not Get Ip Addr"	:"未获取到IP地址",
	"lan_start_tips"	:"DHCP起始IP地址非法,与LAN侧IP地址为不同网段",
	"lan_end_tips"		:"DHCP结束IP地址非法,与LAN侧IP地址为不同网段",
	"limitR_tips"		:"0表示不设限制",
	"CMCC_title"		:"智能组网终端",
	"save power"		:"节能",
	"normal power"		:"标准",
	"full power"		:"穿墙",
	"double freq"		:"WiFi双频合一",
	"double freq switch"		:"WiFi双频合一开关",
	"DNS Server"				:"域名服务器",
	"Auto Config"				:"自动设置",
	"Manual Config"				:"手动设置",
	"To"						:"至",
	"DHCP_range tips"			:"该操作将改变访问IP地址及DHCP地址池范围,请确认?",
	"802.11k_tips"				:"802.11k是一种辅助功能,可以减少漫游所需的时间,通过向客户端提供邻居AP列表及其通道,它允许客户端快速确定下一个应该漫游的AP,客户端不需要探测所有信道以找到用于漫游的候选AP.",
	"BSS transmit"			:"802.11v BSS传输",
	"802.11v_tips"				:"802.11v BSS传输转换管理为AP引入了一个概念,用于将附近的基本服务集加权到客户端,因此,客户端可以使用此信息来做出更好的漫游决策.目前802.11v是在802.11k下定义的.",
	"Separate Clients tips"		:"开启客户端隔离后,各个连接的用户间也不能互相访问,起到隔离作用,有利于抵御外部攻击.",
	"wmm tips"					:"wmm允许无线通信根据数据类型定义一个优先级范围,时间敏感的数据,如视频/音频数据将比普通的数据有更高的优先级.",
	"IP Version"				:"IP协议版本",
	"PD enable"					:"PD使能",
	"DS-Lite enable"			:"DS-Lite启用",
	"Prefix Mode"				:"前缀模式",
	"Prefix Addr"				:"前缀地址",
	"Preferred life"			:"首选寿命:",
	"Effective life"			:"有效寿命:",
	"DS-Lite Mode"				:"DS-Lite模式",
	"DS-Lite Server"			:"DS-Lite服务器",
	"No Encryption"				:"无加密",
	"Not support Chinese and Chinese symbol"		:"不支持中文及中文符号",
	"mactips"					:"开启后能有效的阻止别人蹭WiFi网络,网络更安全,开启后请您选择无线黑名单模式或无线白名单模式",
	"blacktitle"				:"黑名单设备列表",
	"whitetitle"				:"白名单设备列表",
	"Mac list"					:"MAC地址列表",
	"wireless_black"			:"无线黑名单",
	"wireless_white"			:"无线白名单",
	"blacktips"					:"(不允许列表中的设备访问)",
	"whitetips"					:"(只允许列表中的设备访问)",
	"operations"				:"操作",
	"add device"				:"添加设备",
	"delete device"				:"删除设备",
	"select file"				:"选择文件",
	"Online Client"				:"在线客户端",
	"BndStrgTips"				:"开启双频合一将会默认修改5G WiFi名称,加密方式,WiFi密码与2.4G WiFi名称,加密方式以及密码一致,是否开启?",
	"BndStrgssidTips"			:"请修改2.4G WiFi名称与5G WiFi名称一致",
	"BndStrgpasswdTips"			:"请修改2.4G WiFi密码与5G WiFi密码一致",
	"BndStrgencryTips"			:"请修改2.4G WiFi加密方式与5G WiFi加密方式一致",
	"userempty"					:"登录用户名不能为空",
	"userChinese"					:"登录用户名不能为中文",
	"pwdChinese"					:"登录密码不能为中文",
	"pwdempty"					:"登录用户密码不能为空",
	"Only support numbers, letters, -, and_"	:"仅支持数字、字母、中划线和下划线",
	"Year"		:"年",
	"Month"		:"月",
	"Day"		:"日",
	"hour"		:"时",
	"minute"	:"分",
	"second"	:"秒",
	"wanLinkState"			:"WAN口状态",
	"wanLinkRate"			:"上联协商速率",
	"wanCheckFrownInfo1"	:"请检查上联网线/设备 !!",
	"wanCheckFrownInfo2"	:"请检查网线是否连接 !",
	"wifiSaveTips"			:"将应用当前配置生效,是否确认",
	"wifiResetTips"			:"WiFi将会重启,需重新连接",
	"Reveal"				:"显示",
	"hide"					:"隐藏",
	"fwsameTips"			:"当前设备固件版本与升级固件版本一致,不需要重复升级!",	
	"Start Bridge Mode"		:"启用桥接模式",
	"Start Route Mode"		:"启用路由模式",
	"Start 2.4G Repeater"	:"启用2.4G中继模式",
	"Start 5G Repeater"		:"启用5G中继模式",
	"Static v6 Address"		:"静态v6地址",
	"Device Model"			:"设备型号",
	"Device SN"				:"设备SN",
	"v6defaultgwtips"			:"(IPv6默认网关不填内容,则自动获取)",
	"enable"    :"使能",
	"configmodel" :"配置模式:",
	"Manual"  :"手动配置",
	"previous len"   :"前缀长度:",
	"is bot a valid IPv6 address"  :"不是合法的IPv6地址",
	"Previous"   :"前缀",
	"Default Gateway"   :"默认网关",
	"RA maximum interval" :"RA最大间隔:",
	"RA minimum interval" :"RA最小间隔:",
	"less than" :   "小于",
	"less than 0.75 times":"不应大于0.75倍RA最大间隔",
	"open the mamage" :"开启Managed标志",
	"open the other"   :"开启Other标志",
	"dhcpserver"  :"服务器:",
	"auto cpmfig previous and server" :"自动配置前缀和域名服务器",
	"auto config DNS"  :"自动配置域名服务器",
	"malloc addr format"  :"分配地址格式:",
	"DHCP addr pool format" :"地址池格式",
	"EUI64 format":   "EUI64地址格式",
	"RA Config"   :"RA配置",
	"DisConnected"        	: "连接已断开",
	"EasyMesh"						:"EasyMesh",
	"EasyMesh Basic Set"			:"基本设置",
	"EasyMesh More Set"				:"更多设置",
	"EasyMesh Action"				:"行为控制",
	"EasyMesh Status"				:"状态",
	"EasyMesh switch"				:"EasyMesh开关",
	"Device role"					:"设备角色",
	"Back-Haul connection status"	:"回传连接状态",
	"Back-Haul steering"			:"回传转向",
	"EasyMesh On-board"				:"一键组网",
	"Trigger WiFi On-board"			:"启动组网",
	"EasyMesh Select Role"			:"EasyMesh角色切换",
	"EasyMesh Set"					:"EasyMesh设置",
	"EasyMesh Advanced Set"			:"高级设置",
	"2.4G channel Utilization Threshold"	:"2.4G信道利用率",
	"5G channel Utilization Threshold"		:"5G信道利用率",
	"AP sterring RSSI Threshold"			:"AP转向RSSI阀值",
	"Scan Threshold"						:"扫描阀值",
	"BSS Set"								:"BSS 设置",
	"Select Wireless Protocol"				:"选择无线协议",
	"Select SSID"							:"选择SSID",
	"Wireless Name"							:"WiFi名称",
	"Auth Mode"								:"认证模式",
	"Encry Type"							:"加密方式",
	"Back-Haul Support"						:"回传支持",
	"Front-Haul Support"					:"前传支持",
	"Channel Planning"						:"信道规划",
	"Channel Force Switching"				:"信道强制切换",
	"Targel AL-MAC"							:"目标 AL-MAC",
	"Mandate Steering on Agent"				:"转向引导",
	"Targel SSID"							:"目标BSSID",
	"Back-Haul Steering"					:"回传转向",
	"Front-Haul WPS"						:"前传WPS",
	"Front-haul BSS MAC"					:"前传BSS MAC",
	"Up-Link Select"						:"Up-Link 选择",
	"Trigger Up-Link Select"				:"触发Up-Link 选择",
	"Wireless Back-Haul Preference"			:"回传优先级",
	"2.4G Preference"						:"2.4G优先级",
	"5G Preference"							:"5G优先级",
	"Runtime Topology"						:"运行拓扑图",
	"All Device Info"						:"所有设备信息",
	"AP Interface List"						:"AP接口列表",
	"Front-Haul BSS Info"					:"前传BSS信息",
	"Controller Back-haul Status"			:"Controller回传BSS状态",
	"Display"								:"显示",
	"Roaming threshold"						:"漫游阀值",
	"Steer roaming threshold"				:"转向漫游阀值",
	"Force roaming threshold"				:"强制漫游阀值",
	"Only Controller !"												:"Controller可以进行更多设置!",
	"Please open EasyMesh !"										:"需开启EasyMesh,才可进行行为控制!",
	"Agent do not setting wan!"										:"Agent不允许修改上网配置参数",
	"Agent do not setting wifi!"									:"Agent不允许修改无线配置参数",
	"Please input channel !"										:"请输入信道参数!",
	"Targel AL-MAC input err! erg:AA:BB:CC:DD:EE:FF"				:"目标AL-MAC格式输入错误!正确格式为:AA:BB:CC:DD:EE:FF",
	"STA MAC input err! erg:AA:BB:CC:DD:EE:FF"						:"STA MAC格式输入错误!正确格式为:AA:BB:CC:DD:EE:FF",
	"BSSID input err! erg:AA:BB:CC:DD:EE:FF"						:"BSSID格式输入错误!正确格式为:AA:BB:CC:DD:EE:FF",
	"Targel SSID input err!"										:"目标BSSID不能为空!",
	"Front-Haul BSS-MAC input err! erg:AA:BB:CC:DD:EE:FF"			:"前传BSS-MAC格式输入错误!正确格式为:AA:BB:CC:DD:EE:FF",
	"2.4G channel Utilization Threshold input err!Range:0~100."	:"2.4G信道利用率输入错误!数值范围:0~100",
	"5G channel Utilization Threshold input err!Range:0~100."		:"5G信道利用率输入错误!数值范围:0~100",
	"AP sterring RSSI Threshold input err!Range:-90~0."			:"AP转向RSSI阀值输入错误!数值范围:-90~0",
	"AP sterring scan Threshold input err!Range:-90~0."			:"扫描阀值输入错误!数值范围:-90~0",
	"Roaming threshold input err!Range:-90~0."						:"漫游阀值输入错误!数值范围:-90~0",
	"Please wait while the settings are being applied."				:"EasyMesh参数设置中!大概需要15秒,请等待...",
	"EasyMesh On-board Success !"									:"EasyMesh一键组网触发成功!",
	"Please wait while the settings are being applied.After about 1 minutes, manually refresh the page."	:"EasyMesh角色切换中!大概需要1分钟,请等待...切换成功后,页面会自动刷新",
	"If you want to use Wi-Fi connection, please plug out the ethernet cable"	:"如果要切换到WiFI连接,请断开网线",
	"Back-Haul BSS must be configed one and only one!"	:"回传支持必须勾选并且只能勾选一个!",
	"EasyMesh Open!After about 1 minutes, manually refresh the page."	:"EasyMesh开启中!大概需要1分钟,请等待...",
	"IPv6 Wan tips":	"IPv6 WAN信息获取方式",
	"Seconds"			:"秒",
	"Days"				:"天",
	"reboot_week_tips"	:"请至少选中一个重启日期设定!",
	"Reboot_Type1"		:"重启任务执行成功",
	"Reboot_Type2"		:"因设备繁忙,重启任务执行失败",
	"Reboot_Type3"		:"因设备繁忙,重启任务顺延",
	"Reboot_Type4"		:"因用户当日存在重启,未执行任务",
	"Reboot_Type5"		:"当前重启任务未到设定时间,未执行",
	"DNS source"		:"域名服务器来源:",
	"encry_2g_none_tips"	:"请设置2.4G WiFi为加密模式,并设置密码",
	"guide_pwd_overlength"	:"请设置2.4G WiFi密码长度小于32位",
	"ssid2g_5g same error tips"	:"请修改2.4G WiFi名称与5G WiFi名称不一致",
	"dhcpserverDisableTips"		:"当前上网方式为'路由模式',在不确定子网中是否存在其他DHCP Server时,不建议关闭设备的DHCP Server,强行关闭,可能会引起网络异常.",
	"MacFilter Mode"			:"过滤模式",
	"WhiteList_tips"	:"白名单 (只允许列表中的设备访问)",
	"BlackList_tips"	:"黑名单 (不允许列表中的设备访问)",
	"whitelistNULLAddTips"	:"当前设备白名单列表为空,是否添加当前主机MAC地址到白名单列表,点击'确定'后,主机MAC地址将添加至白名单列表,请确认?",
	"Index"					:"索引",
	"Setting"				:"设置",
	"less than or equal"	:"小于等于首选寿命:",
	"Effective life must be greater than preferred life"	:"有效寿命必须大于首选寿命!",
	"blacklistTips"			:"当前添加MAC地址为登录主机MAC地址,点击'确定'后,主机将不能访问设备,请确认是否添加?",
	"whitelistdelTips"		:"当前为白名单模式,删除设备中包含当前登录主机MAC地址,点击'确定'后,主机将不能访问设备,请确认是否删除?",
	"blacklistDelTips"		:"当前主机MAC地址包含在黑名单列表中,是否删除主机MAC地址,点击'确定'后,将从黑名单列表中删除主机MAC地址,请确认是否删除?",
	"whitelistAddTips"		:"当前主机MAC地址不包含在白名单列表中,是否添加当前主机MAC地址为白名单列表,点击'确定'后,主机MAC地址将添加至白名单列表,否则设置后会导致设备不能访问,请确认?",
	"whitelistFULLTips"		:"当前主机MAC地址不包含在白名单列表中且已经添加最大8个MAC过滤列表,请点击'确定'后,手动删除一条MAC过滤规则,点击'取消'后,当前主机将不能访问设备,请选择?",
	"wifi_time_swich same tips" 	:"当前添加时间列表中包含相同的时间,不能重复添加!",
	"wifi_time_swich conflict tips" 	:"当前添加时间列表中包含相同的时间,但配置(网络开关)冲突,相同时间不允许添加不同配置!",
	"Plugin"				:"插件",
	"Province One Level PlatForm" :"省一级平台地址(IF6)",
	"IFA OnlineAddr"						:"IFA服务器地址",
	
	
	
	"Online upgrade"		:"在线升级",
	"Version status"		:"版本状态",
	"Check for updates"		:"检查更新",
	"new version update"	:"版本更新",
	"Ver-checking"			:"版本检查中...",
	"New-firm downloading"	:"最新固件下载中...",
	"Re-check"				:"重新检查",
	"check network"			:"请检查网络状态!",
	"upgrade immediately"	:"立即更新",
	"The latest version"	:"当前已是最新版本!",
	"New version found"		:"发现新的版本",
	"down-firm complete"	:"固件下载完成!",
	"down-firm error"		:"固件下载出错!",
	"Reacquire"				:"重新获取",
	"wanModeSwitchTips"			:"正在保存参数.网络模式切换,下挂设备需要重新获取地址,花费时间较长,请耐心等待",
	"wifi_time_swich everyday conflict tips" 	:"当前添加时间列表中包含每天,当前时间与每天中的配置(网络开关)冲突,不允许添加!",
	"wifi_time_swich everyday same tips" 	:"当前添加时间列表中包含每天,当前时间与每天中的配置重复,不能重复添加!",
	"Before turning on the dual frequency unity function,Please open"	:"开启双频合一功能之前,请先启用",
	"Before turning on the dual frequency unity function,will be auto open EasyMesh."	:"双频合一功能开启将自动开启easymesh功能",
	"Function"				:"功能",
	"backupTips0"			:"\"配置备份\"将设备当前配置备份,以免配置丢失.\"恢复配置\"将备份配置重新导入设备,使其生效.",
	"backupTips1"			:"为确保设备正常使用,恢复配置时,请导入正确的备份配置文件!",
	"BackupAndRestore"		:"配置备份与恢复",
	"WiFi5 compatibility mode"	:"WiFi5兼容模式",
	"compatibility"				:"兼容",
	"compatibletips"		:"兼容模式WiFi密码与对应频段主WiFi密码一致",
	"compatibletips2"		:"部分Wi-Fi 5设备因网卡驱动较旧,无法扫描到Wi-Fi 6信号时,可以开启此Wi-Fi 5信号.",
	"mesh_repeater_tips"		:"启用中继模式将会默认关闭EasyMesh功能!",
	"Romfile Update Success"	:"配置文件还原成功",
	"wanspeedTitle"				:"WAN口速率设置",
	"1000Mbps FUll Duplex"						:"1000Mbps 全双工",
	"100Mbps FUll Duplex"						:"100Mbps 全双工",
	"10Mbps FUll Duplex"					:"10Mbps 全双工",
	"Auto Negotiation"					:"自动协商",
	"current IP"							:"设备当前网络IP地址为",
	"guide passwd tips"						:"密码长度为8-32位,必须包含数字、字母以及特殊符号(下划线或中划线)",
	"Update firmware tips"			:"自动更新固件",
	"Close update firmware automatically"	:"关闭更新固件",
	"upgrade firmware timely"				:"定时更新固件(手动设置时间检测更新并升级)",
	"auto upgrade firmware"			:"自动更新固件(凌晨3时-5时自动检测更新并升级)",
	"upgrade firmware time setting"	:"定时更新固件时间设定",
	"time format"			:"(格式 小时:分钟 24小时制)",
	"disconect"				:"断开",
	"reconect"				:"重连",
	"Not activated"			:"未启用",
	"Internet"				:"互联网",
	"My Router"				:"我的路由器",
	"Terminal Equipment"	:"终端设备",
	"Controller Router"		:"主路由",
	"Agent Router"			:"从路由",
	"Networking equipment"	:"组网设备",
	"AgentnetworkingSuccTips"	:"EasyMesh组网成功,不允许修改从端参数!!",
	"iptvSetNote"			:"仅支持桥接模式配置",
	"quickly config BndStrg tips"		:"已启用双频合一,不支持配置!",
	"restart tips"				:"您确认要重启设备?",
	"restore tips"				:"您确认要恢复出厂配置?",
	"confirm"					:"确认",
	"Sync Switch"				:"同步开关",
	"Ulink settinng"			:"Ulink设置",
	"ignore update"				:"忽略更新",
	"vlanid same tips"			:"此VLAN ID已经使用!",
	
	
}

var lang = Language[languages];	
